import { StyleSheet, Dimensions } from "react-native";

const screenWidth = Dimensions.get("window").width;

// Light theme colors
const lightColors = {
  background: "#F8FAFC",
  cardBackground: "#FFFFFF",
  headerBackground: "#FFFFFF",
  primaryBlue: "#084F8C",
  primaryWhite: "#084F8C",
  accentBlue: "#084F8C",
  textPrimary: "#1E293B",
  textSecondary: "#64748B",
  textMuted: "#94A3B8",
  borderColor: "#E2E8F0",
  dividerColor: "#E0E7FF",
  inputBackground: "#F8FAFC",
  shadowColor: "#000",
  summaryBackground: "#FFFFFF",
  tabBackground: "#FFFFFF",
  itemsBackground: "#F8FAFC",
  feedbackButtonBg: "#EFF6FF",
  feedbackButtonBorder: "#BFDBFE",
  feedbackButtonText: "#1E40AF",
  modalBackground: "#FFFFFF",
  cancelButtonBorder: "#E2E8F0",
  iconWrapBg: "#F1F5F9",
};

// Dark theme colors
const darkColors = {
  background: "#0F172A",
  cardBackground: "#1E293B",
  headerBackground: "#1E293B",
  primaryBlue: "#3B82F6",
  primaryWhite: "#FFFFFF",
  accentBlue: "#60A5FA",
  textPrimary: "#F1F5F9",
  textSecondary: "#94A3B8",
  textMuted: "#64748B",
  borderColor: "#334155",
  dividerColor: "#334155",
  inputBackground: "#0F172A",
  shadowColor: "#000",
  summaryBackground: "#1E293B",
  tabBackground: "#1E293B",
  itemsBackground: "#0F172A",
  feedbackButtonBg: "#1E3A5F",
  feedbackButtonBorder: "#2563EB",
  feedbackButtonText: "#60A5FA",
  modalBackground: "#1E293B",
  cancelButtonBorder: "#334155",
  iconWrapBg: "#334155",
};

const getStyles = (theme = "light") => {
  const colors = theme === "dark" ? darkColors : lightColors;

  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 20,
      paddingVertical: 16,
      backgroundColor: colors.headerBackground,
      paddingTop: 10,
      borderBottomWidth: 1,
      borderBottomColor: colors.borderColor,
      shadowColor: colors.shadowColor,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: theme === "dark" ? 0.3 : 0.05,
      shadowRadius: 8,
      elevation: 2,
    },
    headerLeft: {
      flexDirection: "row",
      alignItems: "center",
      gap: 15,
      flex: 1,
    },
    headerTitle: {
      fontSize: 26,
      fontFamily: "Pacifico-Regular",
      color: colors.primaryWhite,
      letterSpacing: -0.5,
    },

    // Summary Box
    summaryBox: {
      flexDirection: "row",
      justifyContent: "space-around",
      backgroundColor: colors.summaryBackground,
      margin: 20,
      borderRadius: 20,
      paddingVertical: 16,
      shadowColor: colors.primaryBlue,
      shadowOpacity: theme === "dark" ? 0.3 : 0.12,
      shadowRadius: 20,
      elevation: 8,
      borderWidth: 2,
      borderColor: colors.dividerColor,
    },
    summaryItem: { alignItems: "center", flex: 1 },
    summaryLabel: {
      fontSize: 12,
      color: colors.textMuted,
      marginBottom: 4,
      fontWeight: "600",
    },
    summaryValue: { fontSize: 16, fontWeight: "700" },
    divider: {
      width: 1,
      backgroundColor: colors.dividerColor,
      marginHorizontal: 8,
    },

    // Tabs
    tabBar: {
      flexDirection: "row",
      backgroundColor: colors.tabBackground,
      borderRadius: 16,
      marginHorizontal: 20,
      marginBottom: 16,
      overflow: "hidden",
      elevation: 2,
      borderWidth: theme === "dark" ? 1 : 0,
      borderColor: colors.borderColor,
    },
    tab: { flex: 1, paddingVertical: 12, alignItems: "center" },
    tabText: { fontSize: 14, color: colors.textSecondary, fontWeight: "600" },
    tabTextActive: { color: colors.primaryBlue },
    tabIndicator: {
      position: "absolute",
      bottom: 0,
      width: (screenWidth - 40) / 4,
      height: 3,
      backgroundColor: colors.primaryBlue,
    },

    content: {
      flex: 1,
      paddingHorizontal: 20,
    },

    centerContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: colors.background,
    },

    emptyContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      padding: 32,
    },
    emptyTitle: {
      fontSize: 22,
      fontWeight: "700",
      color: colors.textPrimary,
      marginTop: 16,
    },
    emptyText: {
      fontSize: 14,
      color: colors.textSecondary,
      marginTop: 8,
      textAlign: "center",
      fontWeight: "500",
    },
    shopBtn: {
      marginTop: 24,
      paddingHorizontal: 32,
      paddingVertical: 14,
      backgroundColor: colors.accentBlue,
      borderRadius: 12,
      shadowColor: colors.accentBlue,
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.3,
      shadowRadius: 6,
      elevation: 3,
    },
    shopBtnText: {
      color: "#FFFFFF",
      fontSize: 16,
      fontWeight: "700",
    },

    // Order Card
    orderCard: {
      backgroundColor: colors.cardBackground,
      borderRadius: 20,
      padding: 18,
      marginBottom: 16,
      shadowColor: colors.primaryBlue,
      shadowOpacity: theme === "dark" ? 0.3 : 0.1,
      shadowRadius: 15,
      elevation: 4,
      borderWidth: 1,
      borderColor: colors.borderColor,
    },
    orderHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 14,
      paddingBottom: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.borderColor,
    },
    orderHeaderLeft: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    iconWrap: {
      backgroundColor: colors.iconWrapBg,
      padding: 8,
      borderRadius: 12,
    },
    invoiceNumber: {
      fontSize: 15,
      fontWeight: "700",
      color: colors.textPrimary,
    },
    cardDate: {
      fontSize: 12,
      color: colors.textMuted,
      marginTop: 2,
    },
    statusBadge: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 12,
    },
    statusText: {
      fontSize: 11,
      fontWeight: "700",
    },

    orderInfo: {
      flexDirection: "row",
      gap: 20,
      marginBottom: 16,
    },
    infoRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    infoText: {
      fontSize: 13,
      color: colors.textSecondary,
      fontWeight: "500",
    },

    itemsContainer: {
      gap: 12,
      marginBottom: 16,
      backgroundColor: colors.itemsBackground,
      padding: 12,
      borderRadius: 12,
    },
    itemRow: {
      flexDirection: "row",
      justifyContent: "space-between",
    },
    itemInfo: {
      flex: 1,
      marginRight: 12,
    },
    itemName: {
      fontSize: 14,
      fontWeight: "600",
      color: colors.textPrimary,
      marginBottom: 4,
    },
    itemDesc: {
      fontSize: 12,
      color: colors.textMuted,
      marginBottom: 6,
    },
    typeBadge: {
      alignSelf: "flex-start",
      backgroundColor: colors.cardBackground,
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 6,
      borderWidth: 1,
      borderColor: colors.borderColor,
    },
    typeBadgeText: {
      fontSize: 10,
      fontWeight: "600",
      color: colors.textSecondary,
    },
    itemRight: {
      alignItems: "flex-end",
    },
    itemPrice: {
      fontSize: 14,
      fontWeight: "600",
      color: colors.textPrimary,
    },
    discountText: {
      fontSize: 11,
      color: "#10B981",
      marginTop: 2,
      fontWeight: "600",
    },

    orderFooter: {
      gap: 12,
    },
    totalRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    totalLabel: {
      fontSize: 14,
      fontWeight: "600",
      color: colors.textSecondary,
    },
    totalAmount: {
      fontSize: 18,
      fontWeight: "800",
      color: colors.primaryBlue,
    },
    actionRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginTop: 4,
    },
    paymentBadge: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 8,
      backgroundColor: colors.itemsBackground,
    },
    paymentText: {
      fontSize: 12,
      fontWeight: "600",
      color: colors.textSecondary,
    },
    checkoutBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      backgroundColor: colors.primaryBlue,
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 12,
      shadowColor: colors.primaryBlue,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 8,
      elevation: 4,
    },
    checkoutBtnText: {
      color: "#FFFFFF",
      fontSize: 13,
      fontWeight: "700",
    },

    // Pagination
    paginationContainer: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 20,
    },
    paginationBtn: {
      padding: 8,
      borderRadius: 8,
      backgroundColor: colors.cardBackground,
      borderWidth: 1,
      borderColor: colors.borderColor,
    },
    paginationBtnDisabled: {
      opacity: 0.5,
      backgroundColor: colors.itemsBackground,
    },
    pageIndicator: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      marginHorizontal: 16,
      gap: 8,
    },
    pageDot: {
      width: 32,
      height: 32,
      borderRadius: 16,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.cardBackground,
      borderWidth: 1,
      borderColor: colors.borderColor,
    },
    pageDotActive: {
      backgroundColor: colors.primaryBlue,
      borderColor: colors.primaryBlue,
      shadowColor: colors.primaryBlue,
      shadowOpacity: 0.3,
      shadowRadius: 4,
      elevation: 2,
    },
    pageNumber: {
      fontSize: 12,
      fontWeight: "600",
      color: colors.textSecondary,
    },
    pageNumberActive: {
      color: "#FFFFFF",
    },

    // Feedback Styles
    feedbackButton: {
      flexDirection: "row",
      alignItems: "center",
      marginTop: 8,
      paddingVertical: 6,
      paddingHorizontal: 12,
      backgroundColor: colors.feedbackButtonBg,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.feedbackButtonBorder,
      alignSelf: "flex-start",
    },
    feedbackButtonText: {
      fontSize: 12,
      fontWeight: "600",
      color: colors.feedbackButtonText,
      marginLeft: 6,
    },
    modalOverlay: {
      flex: 1,
      justifyContent: "flex-end",
      backgroundColor: "rgba(0, 0, 0, 0.5)",
    },
    modalBackdrop: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
    },
    modalContent: {
      backgroundColor: colors.modalBackground,
      borderTopLeftRadius: 32,
      borderTopRightRadius: 32,
      padding: 24,
      maxHeight: "85%",
      shadowColor: colors.shadowColor,
      shadowOffset: { width: 0, height: -4 },
      shadowOpacity: 0.1,
      shadowRadius: 12,
      elevation: 8,
    },
    modalHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-start",
      marginBottom: 24,
    },
    modalTitle: {
      fontSize: 24,
      fontWeight: "700",
      color: colors.textPrimary,
    },
    modalSubtitle: {
      fontSize: 14,
      color: colors.textSecondary,
      marginTop: 4,
    },
    section: {
      marginBottom: 24,
    },
    sectionTitle: {
      fontSize: 16,
      fontWeight: "600",
      color: colors.textPrimary,
      marginBottom: 12,
    },
    starsContainer: {
      flexDirection: "row",
      justifyContent: "center",
      gap: 8,
      paddingVertical: 12,
    },
    starButton: {
      padding: 4,
    },
    ratingText: {
      textAlign: "center",
      fontSize: 16,
      fontWeight: "600",
      color: "#FFB300",
      marginTop: 8,
    },
    commentInput: {
      backgroundColor: colors.inputBackground,
      borderWidth: 1,
      borderColor: colors.borderColor,
      borderRadius: 16,
      padding: 16,
      fontSize: 15,
      color: colors.textPrimary,
      minHeight: 120,
    },
    charCount: {
      fontSize: 12,
      color: colors.textMuted,
      textAlign: "right",
      marginTop: 8,
    },
    buttonRow: {
      flexDirection: "row",
      gap: 12,
      marginTop: 8,
    },
    cancelButton: {
      flex: 1,
      paddingVertical: 16,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.cancelButtonBorder,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.cardBackground,
    },
    cancelButtonText: {
      fontSize: 15,
      fontWeight: "600",
      color: colors.textSecondary,
    },
    submitButton: {
      flex: 1,
      flexDirection: "row",
      paddingVertical: 16,
      borderRadius: 16,
      backgroundColor: colors.primaryBlue,
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      shadowColor: colors.primaryBlue,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 4,
    },
    submitButtonDisabled: {
      backgroundColor: theme === "dark" ? "#475569" : "#CBD5E1",
      shadowOpacity: 0,
      elevation: 0,
    },
    submitButtonText: {
      fontSize: 15,
      fontWeight: "600",
      color: "#FFFFFF",
    },
  });
};

export default getStyles;
