import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get("window");
const isTablet = width >= 768;

// Light theme colors
const lightColors = {
  background: "#F0F9FF",
  headerBackground: "#FFFFFF",
  headerTitle: "#084F8C",
  headerBorder: "#E2E8F0",
  heroTitle: "#136bb8ff",
  heroSubtitle: "#475569",
  featureBoxBg: "#FFFFFF",
  featureText: "#0369A1",
  plansMainTitle: "#136bb8ff",
  plansSubTitle: "#475569",
  planCardBg: "#FFFFFF",
  planName: "#084F8C",
  planDesc: "#64748B",
  priceText: "#084F8C",
  periodText: "#64748B",
  chooseBtnNormalBg: "#E0F2FE",
  chooseBtnNormalBorder: "#084F8C",
  chooseBtnDisabledBg: "#E5E7EB",
  chooseBtnDisabledBorder: "#D1D5DB",
  chooseBtnText: "#136bb8ff",
  featureItemText: "#475569",
  trustTitle: "#FFFFFF",
  trustText: "#E0F2FE",
  modalOverlay: "rgba(0, 0, 0, 0.5)",
  modalContentBg: "#FFFFFF",
  modalTitle: "#1E293B",
  modalText: "#475569",
  warningBoxBg: "#FFFBEB",
  warningText: "#B45309",
  planDetailsBoxBg: "#F8FAFC",
  planDetailLabel: "#64748B",
  planDetailText: "#0F172A",
  planDetailSubtext: "#64748B",
  modalCancelBg: "#F1F5F9",
  modalCancelText: "#64748B",
  modalConfirmBg: "#2563EB",
  modalConfirmText: "#FFFFFF",
  errorTitle: "#EF4444",
  errorText: "#374151",
  errorButtonBg: "#EF4444",
  errorButtonText: "#FFFFFF",
  iconColor: "#1E40AF",
  featureIconGradientStart: "#E0F2FE",
  featureIconGradientEnd: "#BAE6FD",
  planCardGradientStart: "#E0F2FE",
  planCardGradientEnd: "#BAE6FD",
  planCardPopularGradientStart: "#5eadf2ff",
  planCardPopularGradientEnd: "#1d7accff",
  planCardActiveGradientStart: "#136bb8ff",
  planCardActiveGradientEnd: "#0251c7ff",
  trustGradientStart: "#136bb8ff",
  trustGradientEnd: "#0251c7ff",
  shadowColor: "#000",
};

// Dark theme colors
const darkColors = {
  background: "#0F172A",
  headerBackground: "#1E293B",
  headerTitle: "#F8FAFC",
  headerBorder: "#334155",
  heroTitle: "#F8FAFC",
  heroSubtitle: "#94A3B8",
  featureBoxBg: "#1E293B",
  featureText: "#F8FAFC",
  plansMainTitle: "#F8FAFC",
  plansSubTitle: "#94A3B8",
  planCardBg: "#1E293B",
  planName: "#F8FAFC",
  planDesc: "#CBD5E1",
  priceText: "#F8FAFC",
  periodText: "#94A3B8",
  chooseBtnNormalBg: "#1E3A8A",
  chooseBtnNormalBorder: "#F8FAFC",
  chooseBtnDisabledBg: "#334155",
  chooseBtnDisabledBorder: "#475569",
  chooseBtnText: "#F8FAFC",
  featureItemText: "#CBD5E1",
  trustTitle: "#FFFFFF",
  trustText: "#E0F2FE",
  modalOverlay: "rgba(0, 0, 0, 0.7)",
  modalContentBg: "#1E293B",
  modalTitle: "#F8FAFC",
  modalText: "#CBD5E1",
  warningBoxBg: "#451a03",
  warningText: "#fbbf24",
  planDetailsBoxBg: "#0F172A",
  planDetailLabel: "#94A3B8",
  planDetailText: "#F8FAFC",
  planDetailSubtext: "#94A3B8",
  modalCancelBg: "#334155",
  modalCancelText: "#94A3B8",
  modalConfirmBg: "#2563EB",
  modalConfirmText: "#FFFFFF",
  errorTitle: "#EF4444",
  errorText: "#E5E7EB",
  errorButtonBg: "#EF4444",
  errorButtonText: "#FFFFFF",
  iconColor: "#FFFFFF",
  featureIconGradientStart: "#1E3A8A",
  featureIconGradientEnd: "#172554",
  planCardGradientStart: "#1E293B",
  planCardGradientEnd: "#0F172A",
  planCardPopularGradientStart: "#2563EB",
  planCardPopularGradientEnd: "#1D4ED8",
  planCardActiveGradientStart: "#1E40AF",
  planCardActiveGradientEnd: "#172554",
  trustGradientStart: "#1E40AF",
  trustGradientEnd: "#172554",
  shadowColor: "#000",
};

const getStyles = (theme = "light") => {
  const colors = theme === "dark" ? darkColors : lightColors;

  return StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 20,
      paddingVertical: 16,
      backgroundColor: colors.headerBackground,
      paddingTop: 40,
      borderBottomWidth: 1,
      borderBottomColor: colors.headerBorder,
      shadowColor: colors.shadowColor,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: theme === "dark" ? 0.3 : 0.05,
      shadowRadius: 8,
      elevation: 2,
    },
    headerLeft: {
      flexDirection: "row",
      alignItems: "center",
      gap: 15,
      flex: 1,
    },
    headerTitle: {
      fontSize: 26,
      fontFamily: "Pacifico-Regular",
      color: colors.headerTitle,
      letterSpacing: -0.5,
    },
    scrollContent: { paddingBottom: 40 },
    hero: {
      alignItems: "center",
      padding: 32,
      paddingTop: 20,
    },
    heroTitle: {
      fontSize: isTablet ? 58 : 50,
      fontFamily: "Pacifico-Regular",
      color: colors.heroTitle,
      textAlign: "center",
      lineHeight: isTablet ? 58 : 48,
      marginBottom: 16,
    },
    heroSubtitle: {
      fontSize: 18,
      color: colors.heroSubtitle,
      textAlign: "center",
      fontWeight: "500",
      lineHeight: 28,
      maxWidth: 700,
    },
    featuresGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "center",
      paddingHorizontal: 20,
      gap: 16,
      marginVertical: 32,
    },
    featureBox: {
      width: isTablet ? 180 : (width - 56) / 2,
      backgroundColor: colors.featureBoxBg,
      padding: 20,
      borderRadius: 24,
      alignItems: "center",
      shadowColor: colors.shadowColor,
      shadowOpacity: theme === "dark" ? 0.3 : 0.1,
      shadowRadius: 12,
      elevation: 6,
    },
    featureIcon: {
      width: 64,
      height: 64,
      borderRadius: 32,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 12,
    },
    featureText: {
      fontSize: 14,
      fontWeight: "700",
      color: colors.featureText,
      textAlign: "center",
    },
    plansContainer: { paddingHorizontal: 20, alignItems: "center" },
    plansMainTitle: {
      fontSize: 32,
      fontFamily: "Pacifico-Regular",
      color: colors.plansMainTitle,
      textAlign: "center",
      marginBottom: 8,
    },
    plansSubTitle: {
      fontSize: 18,
      color: colors.plansSubTitle,
      marginBottom: 40,
      fontWeight: "500",
    },
    plansGridCompact: {
      flexDirection: "row",
      gap: 14,
      alignItems: "center",
    },
    planWrapperCompact: {
      width: 280, // Đúng kích thước để 4 card vừa màn hình
      marginHorizontal: 8,
    },
    planCardCompact: {
      borderRadius: 24,
      padding: 20,
      height: 350,
      borderWidth: 2,
      borderColor: "transparent",
      backgroundColor: colors.planCardBg,
      shadowColor: colors.shadowColor,
      shadowOpacity: theme === "dark" ? 0.3 : 0.08,
      shadowRadius: 16,
      elevation: 10,
      justifyContent: "space-between",
    },
    planCardPopularCompact: {
      borderColor: "#1887e8ff",
      shadowColor: "#136bb8ff",
      shadowOpacity: 0.25,
      elevation: 16,
      transform: [{ scale: 1.04 }],
    },
    planCardActiveCompact: {
      borderColor: "#1887e8ff",
      shadowColor: "#136bb8ff",
      shadowOpacity: 0.25,
      elevation: 16,
      transform: [{ scale: 1.05 }],
    },
    planCardInactiveCompact: {
      opacity: 1,
    },
    popularBadgeCompact: {
      position: "absolute",
      top: 4,
      alignSelf: "center",
      backgroundColor: "#F59E0B",
      paddingHorizontal: 14,
      paddingVertical: 6,
      borderRadius: 20,
      zIndex: 10,
    },
    popularTextCompact: {
      color: "#FFF",
      fontSize: 11,
      fontWeight: "800",
    },
    activeBadgeCompact: {
      position: "absolute",
      top: 8,
      right: 12,
      backgroundColor: "#10B981",
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 16,
      zIndex: 10,
    },
    activeTextCompact: {
      color: "#FFF",
      fontSize: 11,
      fontWeight: "800",
    },
    planNameCompact: {
      fontSize: 20,
      fontWeight: "800",
      textAlign: "center",
      color: colors.planName,
      marginTop: 16,
    },
    planDescCompact: {
      fontSize: 13,
      color: colors.planDesc,
      textAlign: "center",
      lineHeight: 18,
      flex: 1,
      marginVertical: 8,
    },
    priceBoxCompact: {
      alignItems: "center",
      marginVertical: 16,
    },
    priceCompact: {
      fontSize: 30,
      fontWeight: "900",
      color: colors.priceText,
    },
    periodCompact: {
      fontSize: 14,
      color: colors.periodText,
      marginTop: 4,
    },
    chooseBtnCompact: {
      paddingVertical: 14,
      borderRadius: 16,
      alignItems: "center",
      justifyContent: "center",
      marginTop: 8,
    },
    chooseBtnPopularCompact: {
      backgroundColor: "#FFFFFF",
    },
    chooseBtnNormalCompact: {
      backgroundColor: colors.chooseBtnNormalBg,
      borderWidth: 2,
      borderColor: colors.chooseBtnNormalBorder,
    },
    chooseBtnDisabledCompact: {
      backgroundColor: colors.chooseBtnDisabledBg,
      borderWidth: 2,
      borderColor: colors.chooseBtnDisabledBorder,
    },
    chooseBtnTextCompact: {
      fontSize: 16,
      fontWeight: "800",
      color: colors.chooseBtnText,
    },
    featuresListCompact: {
      marginTop: 20,
      gap: 10,
    },
    featureRowCompact: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    featureItemCompact: {
      fontSize: 12.5,
      color: colors.featureItemText,
      flex: 1,
    },
    trustSection: {
      marginHorizontal: 20,
      marginTop: 60,
      padding: 20,
      borderRadius: 32,
      alignItems: "center",
      shadowColor: colors.shadowColor,
      shadowOpacity: 0.2,
      elevation: 15,
    },
    trustTitle: {
      fontSize: 26,
      fontWeight: "800",
      color: colors.trustTitle,
      marginTop: 16,
      fontFamily: "Pacifico-Regular",
    },
    trustText: {
      color: colors.trustText,
      textAlign: "center",
      marginTop: 12,
      fontSize: 16,
      lineHeight: 24,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: colors.modalOverlay,
      justifyContent: "center",
      alignItems: "center",
      padding: 20,
    },
    modalContent: {
      width: "100%",
      maxWidth: 400,
      backgroundColor: colors.modalContentBg,
      borderRadius: 24,
      padding: 24,
      alignItems: "center",
      shadowColor: colors.shadowColor,
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.25,
      shadowRadius: 20,
      elevation: 10,
    },
    topAccent: {
      width: 40,
      height: 4,
      backgroundColor: "#E2E8F0",
      borderRadius: 2,
      marginBottom: 20,
    },
    modalTitle: {
      fontSize: 22,
      fontWeight: "800",
      color: colors.modalTitle,
      marginBottom: 16,
      textAlign: "center",
    },
    warningBox: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      backgroundColor: colors.warningBoxBg,
      padding: 12,
      borderRadius: 12,
      marginBottom: 16,
      width: "100%",
    },
    warningText: {
      fontSize: 14,
      color: colors.warningText,
      flex: 1,
      fontWeight: "500",
    },
    planDetailsBox: {
      width: "100%",
      backgroundColor: colors.planDetailsBoxBg,
      padding: 16,
      borderRadius: 16,
      marginBottom: 12,
    },
    planDetailLabel: {
      fontSize: 13,
      color: colors.planDetailLabel,
      marginBottom: 4,
      fontWeight: "600",
    },
    planDetailText: {
      fontSize: 16,
      fontWeight: "700",
      color: colors.planDetailText,
    },
    planDetailSubtext: {
      fontSize: 13,
      color: colors.planDetailSubtext,
      marginTop: 2,
    },
    modalText: {
      fontSize: 16,
      color: colors.modalText,
      textAlign: "center",
      marginBottom: 24,
      lineHeight: 24,
    },
    modalActions: {
      flexDirection: "row",
      gap: 12,
      width: "100%",
      marginTop: 8,
    },
    modalCancel: {
      flex: 1,
      paddingVertical: 14,
      borderRadius: 14,
      backgroundColor: colors.modalCancelBg,
      alignItems: "center",
    },
    modalCancelText: {
      fontSize: 15,
      fontWeight: "600",
      color: colors.modalCancelText,
    },
    modalConfirm: {
      flex: 1,
      paddingVertical: 14,
      borderRadius: 14,
      backgroundColor: colors.modalConfirmBg,
      alignItems: "center",
    },
    modalConfirmText: {
      fontSize: 15,
      fontWeight: "700",
      color: colors.modalConfirmText,
    },
    errorIconContainer: {
      marginBottom: 16,
    },
    errorTitle: {
      fontSize: 20,
      fontWeight: "700",
      color: colors.errorTitle,
      marginBottom: 8,
      textAlign: "center",
    },
    errorText: {
      fontSize: 15,
      color: colors.errorText,
      textAlign: "center",
      marginBottom: 24,
      lineHeight: 22,
    },
    errorButton: {
      paddingHorizontal: 24,
      paddingVertical: 12,
      borderRadius: 12,
      backgroundColor: colors.errorButtonBg,
      minWidth: 100,
      alignItems: "center",
    },
    errorButtonText: {
      color: colors.errorButtonText,
      fontWeight: "600",
      fontSize: 15,
    },

    // Colors for inline usage
    iconColor: colors.iconColor,
    featureIconGradientStart: colors.featureIconGradientStart,
    featureIconGradientEnd: colors.featureIconGradientEnd,
    planCardGradientStart: colors.planCardGradientStart,
    planCardGradientEnd: colors.planCardGradientEnd,
    planCardPopularGradientStart: colors.planCardPopularGradientStart,
    planCardPopularGradientEnd: colors.planCardPopularGradientEnd,
    planCardActiveGradientStart: colors.planCardActiveGradientStart,
    planCardActiveGradientEnd: colors.planCardActiveGradientEnd,
    trustGradientStart: colors.trustGradientStart,
    trustGradientEnd: colors.trustGradientEnd,
  });
};

export default getStyles;
