import { StyleSheet, Dimensions } from "react-native";
const { width, height } = Dimensions.get("window");

const isTablet = width >= 768;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8FAFC",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 16,
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderBottomColor: "#E2E8F0",
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 8,
    elevation: 2,
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  headerTitle: {
    fontSize: isTablet ? 22 : 18,
    fontWeight: "700",
    color: "#1E40AF",
    textAlign: "center",
    flex: 2,
  },
  headerRight: {
    flex: 1,
  },
  mainScroll: {
    paddingHorizontal: isTablet ? 48 : 20,
    paddingTop: 32,
    paddingBottom: 80,
    maxWidth: isTablet ? 1200 : width,
    alignSelf: "center",
    width: "100%",
  },
  section: {
    marginBottom: isTablet ? 56 : 48,
  },
  sectionTitle: {
    fontSize: isTablet ? 28 : 24,
    fontWeight: "700",
    color: "#1E40AF",
    marginBottom: isTablet ? 24 : 20,
    letterSpacing: -0.5,
  },
  featureGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: isTablet ? 20 : 16,
    justifyContent: "space-between",
  },
  featureBox: {
    width: isTablet ? (width - 136) / 3 : (width - 80) / 2,
    minWidth: isTablet ? 240 : 160,
    borderRadius: 16,
    paddingVertical: isTablet ? 28 : 24,
    paddingHorizontal: isTablet ? 20 : 16,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#BFDBFE",
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 12,
    elevation: 3,
    marginBottom: 12,
  },
  featureText: {
    fontSize: isTablet ? 16 : 14,
    fontWeight: "600",
    color: "#1E40AF",
    textAlign: "center",
    lineHeight: isTablet ? 24 : 22,
    marginTop: 12,
  },
  stepList: {
    gap: isTablet ? 24 : 20,
  },
  stepItem: {
    flexDirection: "row",
    backgroundColor: "#FFFFFF",
    padding: isTablet ? 24 : 20,
    borderRadius: 16,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 12,
    elevation: 3,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    alignItems: "center",
    gap: 16,
  },
  stepIconContainer: {
    borderRadius: 50,
    width: isTablet ? 56 : 48,
    height: isTablet ? 56 : 48,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 8,
    elevation: 2,
  },
  stepTextWrap: {
    flex: 1,
  },
  stepTitle: {
    fontSize: isTablet ? 18 : 16,
    fontWeight: "700",
    color: "#1E40AF",
    marginBottom: 6,
  },
  stepDesc: {
    fontSize: isTablet ? 15 : 14,
    color: "#64748B",
    lineHeight: isTablet ? 22 : 20,
    fontWeight: "500",
  },
  priceSection: {
    alignItems: "center",
    gap: isTablet ? 28 : 24,
    marginTop: isTablet ? 32 : 24,
  },
  priceCard: {
    backgroundColor: "#FFFFFF",
    padding: isTablet ? 36 : 28,
    borderRadius: 20,
    width: "100%",
    maxWidth: isTablet ? 600 : "100%",
    borderWidth: 1,
    borderColor: "#BFDBFE",
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 16,
    elevation: 5,
  },
  decorativeDots: {
    display: "none",
  },
  priceHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  planName: {
    fontSize: isTablet ? 28 : 24,
    fontWeight: "700",
    color: "#1E40AF",
    letterSpacing: -0.5,
  },
  saveBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#10B981",
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 6,
    gap: 6,
  },
  saveText: {
    color: "#FFFFFF",
    fontWeight: "800",
    fontSize: isTablet ? 15 : 13,
  },
  priceTag: {
    flexDirection: "row",
    alignItems: "flex-end",
    marginTop: 8,
  },
  priceValue: {
    fontSize: isTablet ? 56 : 48,
    fontWeight: "800",
    color: "#1E40AF",
    letterSpacing: -1.5,
  },
  priceSub: {
    fontSize: isTablet ? 22 : 20,
    color: "#6B7280",
    marginLeft: 8,
    fontWeight: "700",
    marginBottom: 8,
  },
  trialBadge: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: 16,
    backgroundColor: "#EFF6FF",
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#BFDBFE",
  },
  trialText: {
    fontSize: isTablet ? 16 : 14,
    color: "#2563EB",
    fontWeight: "600",
  },
  buyBtn: {
    flexDirection: "row",
    backgroundColor: "#2563EB",
    borderRadius: 16,
    paddingHorizontal: isTablet ? 48 : 40,
    paddingVertical: isTablet ? 18 : 16,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    shadowColor: "#2563EB",
    shadowOpacity: 0.3,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 16,
    elevation: 5,
  },
  buyText: {
    fontSize: isTablet ? 18 : 16,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  securityRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "#EFF6FF",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#BFDBFE",
  },
  securityText: {
    fontSize: isTablet ? 15 : 14,
    color: "#2563EB",
    fontWeight: "600",
  },
});
