export const lessonStyles = {
  container: { flex: 1, backgroundColor: "#FFFFFF" },
  containerCenter: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "#FFFFFF",
  },
  contentMax: { width: "100%", maxWidth: 1000 },
  header: {
    paddingTop: 18,
    paddingBottom: 14,
    paddingHorizontal: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#F8FAFC",
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
  },
  title: { fontSize: 20, fontWeight: "700", color: "#111827" },
  back: { color: "#4F46E5", fontWeight: "600" },
  // Main split 68/32
  mainRow: { flex: 1, flexDirection: "row" },
  leftCol: {
    width: "68%",
    padding: 16,
    borderRightWidth: 1,
    borderRightColor: "#E5E7EB",
  },
  rightCol: { width: "32%", paddingVertical: 16 },
  playerWrap: {
    width: "100%",
    backgroundColor: "#000000",
    borderRadius: 12,
    overflow: "hidden",
    elevation: 2,
  },
  currentLessonTitle: {
    marginTop: 10,
    fontSize: 17,
    fontWeight: "700",
    color: "#111827",
  },
  content: { flex: 1 },
  sectionTitle: {
    marginTop: 0,
    marginBottom: 10,
    paddingHorizontal: 16,
    fontSize: 16,
    fontWeight: "700",
    color: "#111827",
  },
  // Accordion styles
  sidebar: { flex: 1 },
  moduleBox: {
    marginBottom: 10,
    backgroundColor: "#F9FAFB",
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 10,
    overflow: "hidden",
  },
  moduleHeader: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  moduleTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#111827",
    flex: 1,
    paddingRight: 10,
  },
  moduleMeta: { fontSize: 12, color: "#6B7280" },
  moduleChevron: { fontSize: 16, color: "#6B7280", paddingLeft: 6 },
  lessonsList: { paddingHorizontal: 12, paddingBottom: 10 },
  lessonItem: {
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: "#F3F4F6",
    marginBottom: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  lessonTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#111827",
    flex: 1,
    paddingRight: 10,
  },
  lessonDuration: { fontSize: 12, color: "#6B7280" },
  activeItem: {
    backgroundColor: "#EEF2FF",
    borderWidth: 1,
    borderColor: "#C7D2FE",
  },
};
