import { StyleSheet } from "react-native";

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#F8FAFC",
    },
    header: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 20,
        paddingVertical: 16,
        backgroundColor: "#FFFFFF",
        paddingTop: 10,
        borderBottomWidth: 1,
        borderBottomColor: "#E2E8F0",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    headerLeft: {
        flexDirection: "row",
        alignItems: "center",
        gap: 15,
        flex: 1,
    },
    headerTitle: {
        fontSize: 26,
        fontFamily: "Pacifico-Regular",
        color: "#084F8C",
        letterSpacing: -0.5,
    },
    backButton: {
        padding: 12,
        borderRadius: 30,
        backgroundColor: "#F8FAFC",
        shadowColor: "#000",
        shadowOpacity: 0.05,
        shadowRadius: 6,
        elevation: 3,
    },
    card: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#FFFFFF",
        borderRadius: 20,
        padding: 16,
        marginBottom: 12,
        shadowColor: "#084F8C",
        shadowOpacity: 0.12,
        shadowRadius: 20,
        elevation: 6,
    },
    iconWrap: {
        width: 48,
        height: 48,
        borderRadius: 16,
        justifyContent: "center",
        alignItems: "center",
        marginRight: 12,
    },
    cardTitle: {
        fontSize: 15,
        fontWeight: "700",
        color: "#1E293B",
        marginBottom: 2,
    },
    cardDescription: { fontSize: 13, color: "#94A3B8", marginBottom: 2 },
    cardDate: { fontSize: 12, color: "#64748B" },
    amount: { fontSize: 15, fontWeight: "700" },
    badge: {
        borderRadius: 8,
        paddingHorizontal: 6,
        paddingVertical: 2,
        marginTop: 4,
    },
    badgeText: { fontSize: 10, fontWeight: "600" },
    emptyBox: {
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 40,
    },
    emptyText: { fontSize: 14, color: "#94A3B8", marginTop: 12 },
    loadingContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: "rgba(0,0,0,0.45)",
        justifyContent: "flex-end",
    },
    modalContent: {
        backgroundColor: "#FFFFFF",
        borderTopLeftRadius: 32,
        borderTopRightRadius: 32,
        padding: 24,
        maxHeight: "85%",
        shadowColor: "#084F8C",
        shadowOpacity: 0.15,
        shadowRadius: 25,
        elevation: 12,
        borderWidth: 1,
        borderColor: "#E0E7FF",
    },
    modalHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 20,
        borderBottomWidth: 1,
        borderBottomColor: "#E0E7FF",
        paddingBottom: 12,
    },
    modalTitle: { fontSize: 20, fontWeight: "800", color: "#084F8C" },
    modalIconSection: {
        alignItems: "center",
        marginBottom: 24,
    },
    modalIcon: {
        width: 80,
        height: 80,
        borderRadius: 40,
        justifyContent: "center",
        alignItems: "center",
        marginBottom: 12,
    },
    modalLabel: {
        fontSize: 16,
        fontWeight: "600",
        color: "#64748B",
        marginBottom: 8,
    },
    modalAmount: { fontSize: 28, fontWeight: "700", color: "#1E293B" },
    detailSection: {
        backgroundColor: "#F8FAFF",
        borderRadius: 20,
        padding: 16,
        marginBottom: 16,
    },
    detailRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: "#E0E7FF",
    },
    detailLabel: { fontSize: 14, color: "#64748B", fontWeight: "500" },
    detailValue: { fontSize: 14, color: "#1E293B", fontWeight: "600", maxWidth: '60%', textAlign: 'right' },
    statusBadge: { paddingHorizontal: 12, paddingVertical: 4, borderRadius: 12 },
    statusBadgeText: { fontSize: 12, fontWeight: "600" },
    closeBtn: {
        backgroundColor: "#084F8C",
        paddingVertical: 14,
        borderRadius: 16,
        alignItems: "center",
    },
    closeBtnText: { color: "#FFF", fontWeight: "700", fontSize: 16 },
});