import { StyleSheet } from "react-native";

// Light theme colors
const lightColors = {
  background: "#F8FAFC",
  cardBackground: "#FFFFFF",
  headerBackground: "#FFFFFF",
  primaryBlue: "#084F8C",
  textPrimary: "#1E293B",
  textSecondary: "#64748B",
  textMuted: "#94A3B8",
  borderColor: "#E2E8F0",
  dividerColor: "#E0E7FF",
  shadowColor: "#000",
  emptyIconColor: "#CBD5E1",
  modalOverlay: "rgba(0,0,0,0.45)",
  modalBackground: "#FFFFFF",
  detailSectionBg: "#F8FAFF",
  backButtonBg: "#F8FAFC",
  closeIconColor: "#0F172A",
  loadingColor: "#084F8C",
};

// Dark theme colors
const darkColors = {
  background: "#0F172A",
  cardBackground: "#1E293B",
  headerBackground: "#1E293B",
  primaryBlue: "#60A5FA",
  textPrimary: "#F1F5F9",
  textSecondary: "#94A3B8",
  textMuted: "#64748B",
  borderColor: "#334155",
  dividerColor: "#334155",
  shadowColor: "#000",
  emptyIconColor: "#475569",
  modalOverlay: "rgba(0,0,0,0.7)",
  modalBackground: "#1E293B",
  detailSectionBg: "#0F172A",
  backButtonBg: "#334155",
  closeIconColor: "#F1F5F9",
  loadingColor: "#60A5FA",
};

const getStyles = (theme = "light") => {
  const colors = theme === "dark" ? darkColors : lightColors;

  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 20,
      paddingVertical: 16,
      backgroundColor: colors.headerBackground,
      paddingTop: 10,
      borderBottomWidth: 1,
      borderBottomColor: colors.borderColor,
      shadowColor: colors.shadowColor,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: theme === "dark" ? 0.3 : 0.05,
      shadowRadius: 8,
      elevation: 2,
    },
    headerLeft: {
      flexDirection: "row",
      alignItems: "center",
      gap: 15,
      flex: 1,
    },
    headerTitle: {
      fontSize: 26,
      fontFamily: "Pacifico-Regular",
      color: theme === "dark" ? "#FFFFFF" : colors.primaryBlue,
      letterSpacing: -0.5,
    },
    backButton: {
      padding: 12,
      borderRadius: 30,
      backgroundColor: colors.backButtonBg,
      shadowColor: colors.shadowColor,
      shadowOpacity: theme === "dark" ? 0.3 : 0.05,
      shadowRadius: 6,
      elevation: 3,
    },
    card: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: colors.cardBackground,
      borderRadius: 20,
      padding: 16,
      marginBottom: 12,
      shadowColor: colors.primaryBlue,
      shadowOpacity: theme === "dark" ? 0.3 : 0.12,
      shadowRadius: 20,
      elevation: 6,
      borderWidth: 1,
      borderColor: colors.dividerColor,
    },
    iconWrap: {
      width: 48,
      height: 48,
      borderRadius: 16,
      justifyContent: "center",
      alignItems: "center",
      marginRight: 12,
    },
    cardTitle: {
      fontSize: 15,
      fontWeight: "700",
      color: colors.textPrimary,
      marginBottom: 2,
    },
    cardDescription: {
      fontSize: 13,
      color: colors.textMuted,
      marginBottom: 2,
    },
    cardDate: {
      fontSize: 12,
      color: colors.textSecondary,
    },
    amount: {
      fontSize: 15,
      fontWeight: "700",
    },
    badge: {
      borderRadius: 8,
      paddingHorizontal: 6,
      paddingVertical: 2,
      marginTop: 4,
    },
    badgeText: {
      fontSize: 10,
      fontWeight: "600",
    },
    emptyBox: {
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 40,
    },
    emptyText: {
      fontSize: 14,
      color: colors.textMuted,
      marginTop: 12,
    },
    emptyIconColor: colors.emptyIconColor,
    loadingContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
    },
    loadingColor: colors.loadingColor,
    modalOverlay: {
      flex: 1,
      backgroundColor: colors.modalOverlay,
      justifyContent: "flex-end",
    },
    modalContent: {
      backgroundColor: colors.modalBackground,
      borderTopLeftRadius: 32,
      borderTopRightRadius: 32,
      padding: 24,
      maxHeight: "85%",
      shadowColor: colors.primaryBlue,
      shadowOpacity: 0.15,
      shadowRadius: 25,
      elevation: 12,
      borderWidth: 1,
      borderColor: colors.dividerColor,
    },
    modalHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 20,
      borderBottomWidth: 1,
      borderBottomColor: colors.dividerColor,
      paddingBottom: 12,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: "800",
      color: colors.primaryBlue,
    },
    closeIconColor: colors.closeIconColor,
    modalIconSection: {
      alignItems: "center",
      marginBottom: 24,
    },
    modalIcon: {
      width: 80,
      height: 80,
      borderRadius: 40,
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 12,
    },
    modalLabel: {
      fontSize: 16,
      fontWeight: "600",
      color: colors.textSecondary,
      marginBottom: 8,
    },
    modalAmount: {
      fontSize: 28,
      fontWeight: "700",
      color: colors.textPrimary,
    },
    detailSection: {
      backgroundColor: colors.detailSectionBg,
      borderRadius: 20,
      padding: 16,
      marginBottom: 16,
      borderWidth: theme === "dark" ? 1 : 0,
      borderColor: colors.borderColor,
    },
    detailRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.dividerColor,
    },
    detailLabel: {
      fontSize: 14,
      color: colors.textSecondary,
      fontWeight: "500",
    },
    detailValue: {
      fontSize: 14,
      color: colors.textPrimary,
      fontWeight: "600",
      maxWidth: "60%",
      textAlign: "right",
    },
    statusBadge: {
      paddingHorizontal: 12,
      paddingVertical: 4,
      borderRadius: 12,
    },
    statusBadgeText: {
      fontSize: 12,
      fontWeight: "600",
    },
    closeBtn: {
      backgroundColor: colors.primaryBlue,
      paddingVertical: 14,
      borderRadius: 16,
      alignItems: "center",
    },
    closeBtnText: {
      color: "#FFF",
      fontWeight: "700",
      fontSize: 16,
    },
  });
};

export default getStyles;
