import { StyleSheet, Dimensions } from "react-native";

const { width, height } = Dimensions.get("window");

const lightColors = {
  overlay: "rgba(15, 23, 42, 0.6)",
  background: "#FFFFFF",
  borderColor: "rgba(139, 92, 246, 0.1)",
  headerBorder: "rgba(255, 255, 255, 0.2)",
  avatarBg: "#FFFFFF",
  avatarBorder: "rgba(255, 255, 255, 0.9)",
  headerTitle: "#FFFFFF",
  headerSubtitle: "rgba(255, 255, 255, 0.95)",
  closeButtonBg: "rgba(255, 255, 255, 0.25)",
  closeButtonBorder: "rgba(255, 255, 255, 0.3)",
  loadingBg: "#FAFAFA",
  loadingText: "#64748B",
  messagesListBg: "#FAFAFA",
  messageAvatarBg: "#E2E8F0",
  messageAvatarBorder: "#FFFFFF",
  myMessageBubble: "#5c66f6ff",
  theirMessageBubble: "#FFFFFF",
  theirMessageBorder: "#E2E8F0",
  myMessageText: "#FFFFFF",
  theirMessageText: "#1E293B",
  myMessageTime: "rgba(255, 255, 255, 0.85)",
  theirMessageTime: "#94A3B8",
  emptyText: "#334155",
  emptySubtext: "#64748B",
  inputContainerBg: "#FFFFFF",
  inputContainerBorder: "#E2E8F0",
  inputWrapperBg: "#F8FAFC",
  inputWrapperBorder: "#E2E8F0",
  inputText: "#1E293B",
  inputPlaceholder: "#94A3B8",
  sendButtonBg: "#5c80f6ff",
  sendButtonDisabled: "#CBD5E1",
  iconColor: "#5c66f6ff",
  emptyIconColor: "#C4B5FD",
};

const darkColors = {
  overlay: "rgba(0, 0, 0, 0.8)",
  background: "#1E293B",
  borderColor: "#334155",
  headerBorder: "rgba(255, 255, 255, 0.1)",
  avatarBg: "#1E293B",
  avatarBorder: "rgba(255, 255, 255, 0.5)",
  headerTitle: "#FFFFFF",
  headerSubtitle: "rgba(255, 255, 255, 0.8)",
  closeButtonBg: "rgba(255, 255, 255, 0.15)",
  closeButtonBorder: "rgba(255, 255, 255, 0.2)",
  loadingBg: "#0F172A",
  loadingText: "#9CA3AF",
  messagesListBg: "#0F172A",
  messageAvatarBg: "#334155",
  messageAvatarBorder: "#1E293B",
  myMessageBubble: "#3B82F6",
  theirMessageBubble: "#334155",
  theirMessageBorder: "#475569",
  myMessageText: "#FFFFFF",
  theirMessageText: "#F3F4F6",
  myMessageTime: "rgba(255, 255, 255, 0.7)",
  theirMessageTime: "#9CA3AF",
  emptyText: "#F3F4F6",
  emptySubtext: "#9CA3AF",
  inputContainerBg: "#1E293B",
  inputContainerBorder: "#334155",
  inputWrapperBg: "#0F172A",
  inputWrapperBorder: "#334155",
  inputText: "#F3F4F6",
  inputPlaceholder: "#6B7280",
  sendButtonBg: "#3B82F6",
  sendButtonDisabled: "#475569",
  iconColor: "#818CF8",
  emptyIconColor: "#6366F1",
};

export const getStyles = (theme = "light") => {
  const colors = theme === "dark" ? darkColors : lightColors;

  return StyleSheet.create({
    overlay: {
      flex: 1,
      backgroundColor: colors.overlay,
      justifyContent: "flex-end",
      alignItems: "flex-end",
    },
    overlayTouchable: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
    },
    chatContainer: {
      width: width > 500 ? 420 : width - 24,
      height: height * 0.75,
      maxHeight: 650,
      backgroundColor: colors.background,
      borderTopLeftRadius: 32,
      borderTopRightRadius: 32,
      marginRight: 12,
      marginBottom: 12,
      shadowColor: "#5c7bf6ff",
      shadowOffset: { width: 0, height: -8 },
      shadowOpacity: 0.2,
      shadowRadius: 24,
      elevation: 20,
      overflow: "hidden",
      borderWidth: 1,
      borderColor: colors.borderColor,
    },

    // Header với gradient Sketch theme
    header: {
      paddingTop: 20,
      paddingBottom: 16,
      paddingHorizontal: 20,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      borderBottomWidth: 1,
      borderBottomColor: colors.headerBorder,
    },
    headerContent: {
      flexDirection: "row",
      alignItems: "center",
      flex: 1,
    },
    avatar: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: colors.avatarBg,
      justifyContent: "center",
      alignItems: "center",
      marginRight: 14,
      shadowColor: "#5c69f6ff",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 5,
      borderWidth: 2,
      borderColor: colors.avatarBorder,
    },
    headerText: {
      flex: 1,
    },
    headerTitle: {
      fontSize: 18,
      fontWeight: "800",
      color: colors.headerTitle,
      marginBottom: 4,
      letterSpacing: 0.5,
    },
    headerSubtitle: {
      fontSize: 13,
      color: colors.headerSubtitle,
      fontWeight: "600",
    },
    closeButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: colors.closeButtonBg,
      justifyContent: "center",
      alignItems: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.15,
      shadowRadius: 4,
      borderWidth: 1,
      borderColor: colors.closeButtonBorder,
    },

    // Loading
    loadingContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      gap: 16,
      backgroundColor: colors.loadingBg,
    },
    loadingText: {
      fontSize: 15,
      color: colors.loadingText,
      fontWeight: "600",
    },

    // Messages với Sketch design
    messagesList: {
      paddingHorizontal: 16,
      paddingVertical: 20,
      flexGrow: 1,
      backgroundColor: colors.messagesListBg,
    },
    messageRow: {
      flexDirection: "row",
      alignItems: "flex-end",
      marginBottom: 16,
    },
    messageRowMy: {
      justifyContent: "flex-end",
    },
    messageRowTheir: {
      justifyContent: "flex-start",
    },
    messageAvatar: {
      width: 38,
      height: 38,
      borderRadius: 19,
      backgroundColor: colors.messageAvatarBg,
      justifyContent: "center",
      alignItems: "center",
      marginHorizontal: 8,
      shadowColor: "#5c69f6ff",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
      borderWidth: 2,
      borderColor: colors.messageAvatarBorder,
    },
    messageContainer: {
      maxWidth: "75%",
    },
    messageBubble: {
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderRadius: 20,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 6,
      elevation: 3,
    },
    myMessageBubble: {
      backgroundColor: colors.myMessageBubble,
      borderBottomRightRadius: 6,
      shadowColor: "#5c66f6ff",
      shadowOpacity: 0.25,
    },
    theirMessageBubble: {
      backgroundColor: colors.theirMessageBubble,
      borderBottomLeftRadius: 6,
      borderWidth: 1.5,
      borderColor: colors.theirMessageBorder,
    },
    messageText: {
      fontSize: 15,
      lineHeight: 21,
      marginBottom: 4,
      letterSpacing: 0.2,
    },
    myMessageText: {
      color: colors.myMessageText,
      fontWeight: "500",
    },
    theirMessageText: {
      color: colors.theirMessageText,
      fontWeight: "500",
    },
    messageTime: {
      fontSize: 11,
      fontWeight: "600",
      letterSpacing: 0.3,
    },
    myMessageTime: {
      color: colors.myMessageTime,
      textAlign: "right",
    },
    theirMessageTime: {
      color: colors.theirMessageTime,
      textAlign: "left",
    },

    // Empty state
    emptyContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      paddingVertical: 60,
      paddingHorizontal: 20,
    },
    emptyText: {
      fontSize: 19,
      fontWeight: "800",
      color: colors.emptyText,
      marginTop: 16,
      marginBottom: 8,
    },
    emptySubtext: {
      fontSize: 14,
      color: colors.emptySubtext,
      textAlign: "center",
      fontWeight: "500",
    },

    // Input area với Sketch style
    inputContainer: {
      backgroundColor: colors.inputContainerBg,
      paddingHorizontal: 16,
      paddingVertical: 14,
      borderTopWidth: 1,
      borderTopColor: colors.inputContainerBorder,
      shadowColor: "#5c66f6ff",
      shadowOffset: { width: 0, height: -4 },
      shadowOpacity: 0.08,
      shadowRadius: 12,
      elevation: 8,
    },
    inputWrapper: {
      flexDirection: "row",
      alignItems: "flex-end",
      backgroundColor: colors.inputWrapperBg,
      borderRadius: 26,
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderWidth: 2,
      borderColor: colors.inputWrapperBorder,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 3,
      elevation: 2,
    },
    input: {
      flex: 1,
      fontSize: 15,
      color: colors.inputText,
      paddingVertical: 8,
      maxHeight: 90,
      minHeight: 36,
      fontWeight: "500",
    },
    sendButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.sendButtonBg,
      justifyContent: "center",
      alignItems: "center",
      marginLeft: 10,
      shadowColor: "#5c66f6ff",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.4,
      shadowRadius: 10,
      elevation: 6,
    },
    sendButtonDisabled: {
      backgroundColor: colors.sendButtonDisabled,
      shadowColor: "#000",
      shadowOpacity: 0.1,
      elevation: 2,
    },
    // Expose colors
    colors: colors,
  });
};