import { StyleSheet } from "react-native";

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#F8FAFC",
    },
    header: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 20,
        paddingVertical: 16,
        backgroundColor: "#FFFFFF",
        paddingTop: 40,
        borderBottomWidth: 1,
        borderBottomColor: "#E2E8F0",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    headerLeft: {
        flexDirection: "row",
        alignItems: "center",
        gap: 15,
        flex: 1,
    },
    headerTitle: {
        fontSize: 26,
        fontFamily: "Pacifico-Regular",
        color: "#084F8C",
        letterSpacing: -0.5,
    },
    addButton: {
        backgroundColor: "#084F8C",
        paddingHorizontal: 20,
        paddingVertical: 10,
        borderRadius: 12,
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
    },
    addButtonText: {
        color: "#FFFFFF",
        fontWeight: "700",
        fontSize: 14,
    },

    // List
    scrollContent: {
        padding: 20,
    },
    accountCard: {
        backgroundColor: "#FFFFFF",
        borderRadius: 16,
        padding: 16,
        marginBottom: 16,
        flexDirection: "row",
        alignItems: "center",
        shadowColor: "#000",
        shadowOpacity: 0.1,
        shadowRadius: 12,
        elevation: 4,
        borderWidth: 1,
        borderColor: "#E0E7FF",
    },
    bankLogo: {
        width: 50,
        height: 50,
        borderRadius: 8,
        marginRight: 14,
    },
    accountInfo: {
        flex: 1,
    },
    bankName: {
        fontSize: 16,
        fontWeight: "700",
        color: "#084F8C",
        marginBottom: 4,
    },
    accountNumber: {
        fontSize: 14,
        color: "#64748B",
        marginBottom: 2,
    },
    accountHolder: {
        fontSize: 13,
        color: "#94A3B8",
    },
    defaultBadge: {
        backgroundColor: "#FEF3C7",
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 6,
        marginTop: 6,
        alignSelf: "flex-start",
    },
    defaultText: {
        fontSize: 11,
        fontWeight: "700",
        color: "#92400E",
    },
    actionButtons: {
        flexDirection: "row",
        gap: 8,
    },
    backButton: {
        padding: 4,
    },
    editButton: {
        backgroundColor: "#10B981",
        paddingHorizontal: 14,
        paddingVertical: 10,
        borderRadius: 10,
        flexDirection: "row",
        alignItems: "center",
        gap: 4,
        shadowColor: "#10B981",
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 3,
    },
    deleteButton: {
        backgroundColor: "#EF4444",
        paddingHorizontal: 14,
        paddingVertical: 10,
        borderRadius: 10,
        flexDirection: "row",
        alignItems: "center",
        gap: 4,
        shadowColor: "#EF4444",
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 3,
    },

    // Empty State
    emptyContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        paddingVertical: 60,
    },
    emptyText: {
        fontSize: 16,
        color: "#94A3B8",
        marginTop: 12,
        textAlign: "center",
    },

    // Modal
    modalOverlay: {
        flex: 1,
        backgroundColor: "rgba(0,0,0,0.45)",
        justifyContent: "center",
        alignItems: "center",
        paddingHorizontal: 20,
    },
    modalContent: {
        backgroundColor: "#FFFFFF",
        borderTopLeftRadius: 32,
        borderTopRightRadius: 32,
        maxHeight: "92%",
        paddingBottom: 10,
    },
    modalHeader: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 24,
        paddingTop: 20,
        paddingBottom: 16,
        borderBottomWidth: 1,
        borderBottomColor: "#E6E9F5",
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: "800",
        color: "#084F8C",
    },
    modalBody: {
        padding: 15,
        paddingBottom: 0,
    },
    inputLabel: {
        fontSize: 14,
        fontWeight: "600",
        color: "#475569",
        marginBottom: 6,
        marginTop: 12,
    },
    input: {
        backgroundColor: "#F8FAFF",
        borderRadius: 14,
        paddingVertical: 14,
        paddingHorizontal: 16,
        borderWidth: 1.5,
        borderColor: "#D4DAF3",
        fontSize: 15,
        fontWeight: "600",
        color: "#0F172A",
    },
    modalFooter: {
        flexDirection: "row",
        justifyContent: "center",
        paddingHorizontal: 20,
        paddingVertical: 16,
        paddingBottom: 24,
        gap: 60,
        borderTopWidth: 1,
        borderTopColor: "#E6E9F5",
        backgroundColor: "#FFFFFF",
    },
    button: {
        width: "28%",
        paddingVertical: 16,
        borderRadius: 14,
        alignItems: "center",
        justifyContent: "center",
    },
    cancelButton: {
        backgroundColor: "#F1F5F9",
        borderWidth: 1,
        borderColor: "#E2E8F0",
    },
    confirmButton: {
        backgroundColor: "#084F8C",
        shadowColor: "#084F8C",
        shadowOpacity: 0.25,
        shadowRadius: 10,
        elevation: 6,
    },
    deleteConfirmButton: {
        backgroundColor: "#EF4444",
    },
    buttonText: {
        fontSize: 16,
        fontWeight: "700",
    },

    // Bank Selector
    bankSelectorContainer: {
        backgroundColor: "#F8FAFC",
        borderRadius: 12,
        padding: 12,
        marginTop: 8,
        marginBottom: 16,
        maxHeight: 300,
    },
    searchInput: {
        backgroundColor: "#FFFFFF",
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderWidth: 1,
        borderColor: "#E2E8F0",
        marginBottom: 8,
    },
    bankItem: {
        flexDirection: "row",
        alignItems: "center",
        padding: 10,
        backgroundColor: "#FFFFFF",
        borderRadius: 8,
        marginBottom: 6,
        borderWidth: 1,
        borderColor: "#E2E8F0",
    },
    bankItemSelected: {
        backgroundColor: "#DBEAFE",
        borderColor: "#3B82F6",
    },
    bankItemLogo: {
        width: 40,
        height: 40,
        marginRight: 12,
        borderRadius: 6,
    },
    bankItemInfo: {
        flex: 1,
    },
    bankShortName: {
        fontWeight: "600",
        fontSize: 14,
        color: "#0F172A",
    },
    bankFullName: {
        fontSize: 12,
        color: "#64748B",
    },
    checkmark: {
        width: 20,
        height: 20,
    },
    checkmarkText: {
        color: "#3B82F6",
        fontSize: 16,
    },

    // Delete Modal (Centered)
    deleteModalContent: {
        backgroundColor: "#FFFFFF",
        borderRadius: 20,
        width: "100%",
        maxWidth: 400,
        shadowColor: "#000",
        shadowOpacity: 0.2,
        shadowRadius: 20,
        elevation: 10,
    },
    deleteModalHeader: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 20,
        paddingTop: 16,
        paddingBottom: 12,
        borderBottomWidth: 1,
        borderBottomColor: "#E6E9F5",
    },
    deleteModalBody: {
        padding: 24,
        alignItems: "center",
    },
    deleteModalFooter: {
        flexDirection: "row",
        justifyContent: "center",
        paddingHorizontal: 20,
        paddingVertical: 16,
        paddingBottom: 20,
        gap: 12,
        borderTopWidth: 1,
        borderTopColor: "#E6E9F5",
    },
});
