import { StyleSheet } from "react-native";

// Light theme colors
const lightColors = {
  background: "#F8FAFC",
  cardBackground: "#FFFFFF",
  headerBackground: "#FFFFFF",
  primaryBlue: "#084F8C",
  textPrimary: "#1E293B",
  textSecondary: "#64748B",
  textMuted: "#94A3B8",
  borderColor: "#E2E8F0",
  dividerColor: "#E0E7FF",
  shadowColor: "#000",
  inputBackground: "#F8FAFF",
  inputBorder: "#D4DAF3",
  emptyIconColor: "#CBD5E1",
  modalOverlay: "rgba(0,0,0,0.45)",
  modalBackground: "#FFFFFF",
  modalHeaderBorder: "#E6E9F5",
  bankSelectorBg: "#F8FAFC",
  bankItemBg: "#FFFFFF",
  bankItemSelectedBg: "#DBEAFE",
  bankItemBorder: "#E2E8F0",
  bankItemSelectedBorder: "#3B82F6",
  searchInputBg: "#FFFFFF",
  searchInputBorder: "#E2E8F0",
  cancelButtonBg: "#F1F5F9",
  cancelButtonBorder: "#E2E8F0",
  backButtonBg: "#F8FAFC",
  deleteModalBg: "#F8FAFC",
  closeIconColor: "#0F172A",
  loadingColor: "#084F8C",
};

// Dark theme colors
const darkColors = {
  background: "#0F172A",
  cardBackground: "#1E293B",
  headerBackground: "#1E293B",
  primaryBlue: "#60A5FA",
  textPrimary: "#F1F5F9",
  textSecondary: "#94A3B8",
  textMuted: "#64748B",
  borderColor: "#334155",
  dividerColor: "#334155",
  shadowColor: "#000",
  inputBackground: "#0F172A",
  inputBorder: "#334155",
  emptyIconColor: "#475569",
  modalOverlay: "rgba(0,0,0,0.7)",
  modalBackground: "#1E293B",
  modalHeaderBorder: "#334155",
  bankSelectorBg: "#0F172A",
  bankItemBg: "#1E293B",
  bankItemSelectedBg: "#1E3A5F",
  bankItemBorder: "#334155",
  bankItemSelectedBorder: "#3B82F6",
  searchInputBg: "#0F172A",
  searchInputBorder: "#334155",
  cancelButtonBg: "#334155",
  cancelButtonBorder: "#475569",
  backButtonBg: "#334155",
  deleteModalBg: "#0F172A",
  closeIconColor: "#F1F5F9",
  loadingColor: "#60A5FA",
};

const getStyles = (theme = "light") => {
  const colors = theme === "dark" ? darkColors : lightColors;

  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 20,
      paddingVertical: 16,
      backgroundColor: colors.headerBackground,
      paddingTop: 40,
      borderBottomWidth: 1,
      borderBottomColor: colors.borderColor,
      shadowColor: colors.shadowColor,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: theme === "dark" ? 0.3 : 0.05,
      shadowRadius: 8,
      elevation: 2,
    },
    headerLeft: {
      flexDirection: "row",
      alignItems: "center",
      gap: 15,
      flex: 1,
    },
    headerTitle: {
      fontSize: 26,
      fontFamily: "Pacifico-Regular",
      color: theme === "dark" ? "#FFFFFF" : colors.primaryBlue,
      letterSpacing: -0.5,
    },
    addButton: {
      backgroundColor: colors.primaryBlue,
      paddingHorizontal: 20,
      paddingVertical: 10,
      borderRadius: 12,
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    addButtonText: {
      color: "#FFFFFF",
      fontWeight: "700",
      fontSize: 14,
    },

    // List
    scrollContent: {
      padding: 20,
    },
    accountCard: {
      backgroundColor: colors.cardBackground,
      borderRadius: 16,
      padding: 16,
      marginBottom: 16,
      flexDirection: "row",
      alignItems: "center",
      shadowColor: colors.shadowColor,
      shadowOpacity: theme === "dark" ? 0.3 : 0.1,
      shadowRadius: 12,
      elevation: 4,
      borderWidth: 1,
      borderColor: colors.dividerColor,
    },
    bankLogo: {
      width: 50,
      height: 50,
      borderRadius: 8,
      marginRight: 14,
    },
    accountInfo: {
      flex: 1,
    },
    bankName: {
      fontSize: 16,
      fontWeight: "700",
      color: colors.primaryBlue,
      marginBottom: 4,
    },
    accountNumber: {
      fontSize: 14,
      color: colors.textSecondary,
      marginBottom: 2,
    },
    accountHolder: {
      fontSize: 13,
      color: colors.textMuted,
    },
    defaultBadge: {
      backgroundColor: theme === "dark" ? "#78350F" : "#FEF3C7",
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 6,
      marginTop: 6,
      alignSelf: "flex-start",
    },
    defaultText: {
      fontSize: 11,
      fontWeight: "700",
      color: theme === "dark" ? "#FCD34D" : "#92400E",
    },
    actionButtons: {
      flexDirection: "row",
      gap: 8,
    },
    backButton: {
      padding: 12,
      borderRadius: 30,
      backgroundColor: colors.backButtonBg,
      shadowColor: colors.shadowColor,
      shadowOpacity: theme === "dark" ? 0.3 : 0.05,
      shadowRadius: 6,
      elevation: 3,
    },
    editButton: {
      backgroundColor: "#10B981",
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 10,
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      shadowColor: "#10B981",
      shadowOpacity: 0.25,
      shadowRadius: 4,
      elevation: 3,
    },
    deleteButton: {
      backgroundColor: "#EF4444",
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 10,
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      shadowColor: "#EF4444",
      shadowOpacity: 0.25,
      shadowRadius: 4,
      elevation: 3,
    },

    // Empty State
    emptyContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      paddingVertical: 60,
    },
    emptyText: {
      fontSize: 16,
      color: colors.textMuted,
      marginTop: 12,
      textAlign: "center",
    },
    emptyIconColor: colors.emptyIconColor,

    // Loading
    loadingColor: colors.loadingColor,

    // Modal
    modalOverlay: {
      flex: 1,
      backgroundColor: colors.modalOverlay,
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: 20,
    },
    modalContent: {
      backgroundColor: colors.modalBackground,
      borderTopLeftRadius: 32,
      borderTopRightRadius: 32,
      maxHeight: "92%",
      paddingBottom: 10,
      width: "100%",
    },
    modalHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 24,
      paddingTop: 20,
      paddingBottom: 16,
      borderBottomWidth: 1,
      borderBottomColor: colors.modalHeaderBorder,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: "800",
      color: colors.primaryBlue,
    },
    closeIconColor: colors.closeIconColor,
    modalBody: {
      padding: 15,
      paddingBottom: 0,
    },
    inputLabel: {
      fontSize: 14,
      fontWeight: "600",
      color: colors.textSecondary,
      marginBottom: 6,
      marginTop: 12,
    },
    input: {
      backgroundColor: colors.inputBackground,
      borderRadius: 14,
      paddingVertical: 14,
      paddingHorizontal: 16,
      borderWidth: 1.5,
      borderColor: colors.inputBorder,
      fontSize: 15,
      fontWeight: "600",
      color: colors.textPrimary,
    },
    modalFooter: {
      flexDirection: "row",
      justifyContent: "center",
      paddingHorizontal: 20,
      paddingVertical: 16,
      paddingBottom: 24,
      gap: 60,
      borderTopWidth: 1,
      borderTopColor: colors.modalHeaderBorder,
      backgroundColor: colors.modalBackground,
    },
    button: {
      width: "28%",
      paddingVertical: 16,
      borderRadius: 14,
      alignItems: "center",
      justifyContent: "center",
    },
    cancelButton: {
      backgroundColor: colors.cancelButtonBg,
      borderWidth: 1,
      borderColor: colors.cancelButtonBorder,
    },
    cancelButtonText: {
      color: colors.textSecondary,
    },
    confirmButton: {
      backgroundColor: colors.primaryBlue,
      shadowColor: colors.primaryBlue,
      shadowOpacity: 0.25,
      shadowRadius: 10,
      elevation: 6,
    },
    deleteConfirmButton: {
      backgroundColor: "#EF4444",
    },
    buttonText: {
      fontSize: 16,
      fontWeight: "700",
    },

    // Bank Selector
    bankSelectorContainer: {
      backgroundColor: colors.bankSelectorBg,
      borderRadius: 12,
      padding: 12,
      marginTop: 8,
      marginBottom: 16,
      maxHeight: 300,
      borderWidth: theme === "dark" ? 1 : 0,
      borderColor: colors.borderColor,
    },
    searchInput: {
      backgroundColor: colors.searchInputBg,
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderWidth: 1,
      borderColor: colors.searchInputBorder,
      marginBottom: 8,
      color: colors.textPrimary,
    },
    bankItem: {
      flexDirection: "row",
      alignItems: "center",
      padding: 10,
      backgroundColor: colors.bankItemBg,
      borderRadius: 8,
      marginBottom: 6,
      borderWidth: 1,
      borderColor: colors.bankItemBorder,
    },
    bankItemSelected: {
      backgroundColor: colors.bankItemSelectedBg,
      borderColor: colors.bankItemSelectedBorder,
    },
    bankItemLogo: {
      width: 40,
      height: 40,
      marginRight: 12,
      borderRadius: 6,
    },
    bankItemInfo: {
      flex: 1,
    },
    bankShortName: {
      fontWeight: "600",
      fontSize: 14,
      color: colors.textPrimary,
    },
    bankFullName: {
      fontSize: 12,
      color: colors.textSecondary,
    },
    checkmark: {
      width: 20,
      height: 20,
    },
    checkmarkText: {
      color: "#3B82F6",
      fontSize: 16,
    },

    // Delete Modal (Centered)
    deleteModalContent: {
      backgroundColor: colors.modalBackground,
      borderRadius: 20,
      width: "100%",
      maxWidth: 400,
      shadowColor: colors.shadowColor,
      shadowOpacity: 0.2,
      shadowRadius: 20,
      elevation: 10,
    },
    deleteModalHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 20,
      paddingTop: 16,
      paddingBottom: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.modalHeaderBorder,
    },
    deleteModalBody: {
      padding: 24,
      alignItems: "center",
    },
    deleteModalText: {
      fontSize: 15,
      color: colors.textSecondary,
      textAlign: "center",
      marginBottom: 16,
    },
    deleteModalAccountInfo: {
      alignItems: "center",
      backgroundColor: colors.deleteModalBg,
      padding: 12,
      borderRadius: 12,
      width: "100%",
      borderWidth: theme === "dark" ? 1 : 0,
      borderColor: colors.borderColor,
    },
    deleteModalAccountName: {
      fontWeight: "700",
      color: colors.primaryBlue,
      fontSize: 15,
    },
    deleteModalAccountNumber: {
      color: colors.textSecondary,
      marginTop: 4,
      fontSize: 13,
    },
    deleteModalFooter: {
      flexDirection: "row",
      justifyContent: "center",
      paddingHorizontal: 20,
      paddingVertical: 16,
      paddingBottom: 20,
      gap: 12,
      borderTopWidth: 1,
      borderTopColor: colors.modalHeaderBorder,
    },
  });
};

export default getStyles;
