import { StyleSheet, Dimensions } from "react-native";
const screenWidth = Dimensions.get("window").width;
export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#F8FAFC",
    },
    header: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 20,
        paddingVertical: 16,
        backgroundColor: "#FFFFFF",
        paddingTop: 10,
        borderBottomWidth: 1,
        borderBottomColor: "#E2E8F0",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    headerLeft: {
        flexDirection: "row",
        alignItems: "center",
        gap: 15,
        flex: 1,
    },
    headerTitle: {
        fontSize: 26,
        fontFamily: "Pacifico-Regular",
        color: "#084F8C",
        letterSpacing: -0.5,
    },
    backButton: {
        padding: 12,
        borderRadius: 30,
        backgroundColor: "#F8FAFC",
        shadowColor: "#000",
        shadowOpacity: 0.05,
        shadowRadius: 6,
        elevation: 3,
    },

    summaryBox: {
        flexDirection: "row",
        justifyContent: "space-around",
        backgroundColor: "#FFFFFF",
        margin: 20,
        borderRadius: 20,
        paddingVertical: 16,
        shadowColor: "#084F8C",
        shadowOpacity: 0.12,
        shadowRadius: 20,
        elevation: 8,
        borderWidth: 2,
        borderColor: "#E0E7FF",
    },
    summaryItem: { alignItems: "center", flex: 1 },
    summaryLabel: {
        fontSize: 12,
        color: "#94A3B8",
        marginBottom: 4,
        fontWeight: "600",
    },
    summaryValue: { fontSize: 16, fontWeight: "700" },
    divider: { width: 1, backgroundColor: "#E0E7FF", marginHorizontal: 8 },

    tabBar: {
        flexDirection: "row",
        backgroundColor: "#FFFFFF",
        borderRadius: 16,
        marginHorizontal: 20,
        marginBottom: 10,
        overflow: "hidden",
        elevation: 2,
    },
    tab: { flex: 1, paddingVertical: 12, alignItems: "center" },
    tabText: { fontSize: 14, color: "#64748B", fontWeight: "600" },
    tabTextActive: { color: "#084F8C" },
    tabIndicator: {
        position: "absolute",
        bottom: 0,
        width: screenWidth / 4,
        height: 3,
        backgroundColor: "#084F8C",
    },

    card: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#FFFFFF",
        borderRadius: 20,
        padding: 16,
        marginBottom: 12,
        shadowColor: "#084F8C",
        shadowOpacity: 0.12,
        shadowRadius: 20,
        elevation: 6,
    },
    iconWrap: {
        width: 48,
        height: 48,
        borderRadius: 16,
        justifyContent: "center",
        alignItems: "center",
        marginRight: 12,
    },
    cardTitle: {
        fontSize: 15,
        fontWeight: "700",
        color: "#1E293B",
        marginBottom: 2,
    },
    cardDescription: { fontSize: 13, color: "#94A3B8", marginBottom: 2 },
    cardDate: { fontSize: 12, color: "#64748B" },
    cardCode: { fontSize: 11, color: "#94A3B8", marginTop: 2 },
    amount: { fontSize: 15, fontWeight: "700" },
    badge: {
        borderRadius: 8,
        paddingHorizontal: 6,
        paddingVertical: 2,
        marginTop: 4,
    },
    badgeText: { fontSize: 10, fontWeight: "600" },

    emptyBox: {
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 40,
    },
    emptyText: { fontSize: 14, color: "#94A3B8", marginTop: 12 },

    modalOverlay: {
        flex: 1,
        backgroundColor: "rgba(15, 23, 42, 0.75)",
        justifyContent: "center",
        alignItems: "center",
    },
    modalContent: {
        backgroundColor: "#FFFFFF",
        borderRadius: 20,
        padding: 24,
        width: "85%",
        maxWidth: 420,
        maxHeight: "80%",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.25,
        shadowRadius: 25,
        elevation: 15,
    },
    modalHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 20,
        paddingBottom: 16,
        borderBottomWidth: 1,
        borderBottomColor: "#F1F5F9",
    },
    modalTitle: { fontSize: 20, fontWeight: "700", color: "#0F172A" },

    modalIconSection: {
        alignItems: "center",
        marginBottom: 20,
    },
    modalIcon: {
        width: 64,
        height: 64,
        borderRadius: 32,
        justifyContent: "center",
        alignItems: "center",
        marginBottom: 12,
    },
    modalLabel: {
        fontSize: 15,
        fontWeight: "600",
        color: "#64748B",
        marginBottom: 6,
    },
    modalAmount: { fontSize: 24, fontWeight: "700", color: "#0F172A" },

    detailSection: {
        backgroundColor: "#F8FAFC",
        borderRadius: 16,
        padding: 16,
        marginBottom: 16,
    },
    detailRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingVertical: 10,
        borderBottomWidth: 1,
        borderBottomColor: "#E2E8F0",
    },
    detailLabel: { fontSize: 13, color: "#64748B", fontWeight: "500" },
    detailValue: { fontSize: 13, color: "#0F172A", fontWeight: "600" },
    statusBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 10 },
    statusBadgeText: { fontSize: 11, fontWeight: "600" },

    closeBtn: {
        backgroundColor: "#084F8C",
        paddingVertical: 13,
        borderRadius: 12,
        alignItems: "center",
        shadowColor: "#084F8C",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 6,
    },
    closeBtnText: { color: "#FFF", fontWeight: "700", fontSize: 14 },
});
