import { StyleSheet } from "react-native";

// Light theme colors
const lightColors = {
  background: "#F8FAFC",
  cardBackground: "#FFFFFF",
  headerOverlay: "rgba(0,0,0,0.45)",
  primaryBlue: "#1E40AF",
  accentBlue: "#3B82F6",
  lightBlue: "#EFF6FF",
  borderBlue: "#BFDBFE",
  textPrimary: "#1E3A8A",
  textSecondary: "#6B7280",
  textMuted: "#9CA3AF",
  inputBackground: "#EFF6FF",
  inputBorder: "#BFDBFE",
  disabledBackground: "#E5E7EB",
  disabledText: "#9CA3AF",
  roleBadgeBg: "#DBEAFE",
  roleBadgeText: "#2563EB",
  bankCardBorder: "#BFDBFE",
  bankCardShadow: "#3B82F6",
  defaultBadgeBg: "#10B981",
  modalOverlay: "rgba(0, 0, 0, 0.6)",
  modalBackground: "#FFFFFF",
  searchInputBg: "#F3F4F6",
  searchInputBorder: "#E5E7EB",
  bankItemBorder: "#F3F4F6",
  bankItemSelectedBg: "#EFF6FF",
  cancelButtonBg: "#F3F4F6",
  cancelButtonBorder: "#E5E7EB",
  cancelButtonText: "#374151",
  sectionBorder: "#E5E7EB",
};

// Dark theme colors
const darkColors = {
  background: "#0F172A",
  cardBackground: "#1E293B",
  headerOverlay: "rgba(0,0,0,0.65)",
  primaryBlue: "#60A5FA",
  accentBlue: "#3B82F6",
  lightBlue: "#1E3A5F",
  borderBlue: "#334155",
  textPrimary: "#F1F5F9",
  textSecondary: "#94A3B8",
  textMuted: "#64748B",
  inputBackground: "#0F172A",
  inputBorder: "#334155",
  disabledBackground: "#334155",
  disabledText: "#64748B",
  roleBadgeBg: "#1E3A5F",
  roleBadgeText: "#60A5FA",
  bankCardBorder: "#334155",
  bankCardShadow: "#000000",
  defaultBadgeBg: "#10B981",
  modalOverlay: "rgba(0, 0, 0, 0.8)",
  modalBackground: "#1E293B",
  searchInputBg: "#0F172A",
  searchInputBorder: "#334155",
  bankItemBorder: "#334155",
  bankItemSelectedBg: "#1E3A5F",
  cancelButtonBg: "#334155",
  cancelButtonBorder: "#475569",
  cancelButtonText: "#E2E8F0",
  sectionBorder: "#334155",
};

const getStyles = (theme = "light") => {
  const colors = theme === "dark" ? darkColors : lightColors;

  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    toggleButton: {
      position: "absolute",
      top: 40,
      left: 16,
      zIndex: 10,
    },

    // Header
    headerBackground: {
      width: "100%",
      height: 150,
      justifyContent: "center",
      alignItems: "center",
    },
    headerOverlay: {
      width: "100%",
      height: "100%",
      backgroundColor: colors.headerOverlay,
      justifyContent: "center",
      alignItems: "center",
    },
    headerTitle: {
      fontSize: 40,
      fontFamily: "Pacifico-Regular",
      color: "#FFFFFF",
    },
    headerSubtitle: {
      fontSize: 25,
      fontFamily: "Pacifico-Regular",
      color: "#E2E8F0",
      marginTop: 4,
    },

    // Two Columns
    twoColumnContainer: {
      width: "100%",
      padding: 20,
      gap: 30,
    },
    leftColumn: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
    },
    rightColumn: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      width: "100%",
    },

    // Avatar
    avatarContainer: {
      position: "relative",
      alignItems: "center",
      justifyContent: "center",
    },
    avatarWrapper: {
      width: 420,
      height: 420,
      borderRadius: 240,
      overflow: "hidden",
      backgroundColor: theme === "dark" ? "#334155" : "#E2E8F0",
    },
    avatar: {
      width: "100%",
      height: "100%",
    },
    avatarOverlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: "rgba(0,0,0,0.4)",
      justifyContent: "center",
      alignItems: "center",
    },
    cameraButton: {
      position: "absolute",
      bottom: 30,
      right: 30,
      backgroundColor: colors.accentBlue,
      borderRadius: 55,
      padding: 10,
      borderWidth: 2,
      borderColor: "#FFFFFF",
    },
    cameraIcon: {
      color: "#FFFFFF",
      fontSize: 34,
    },

    premiumRing: {
      position: "absolute",
      width: 460,
      height: 460,
      borderRadius: 230,
      top: -20,
      left: -20,
      justifyContent: "center",
      alignItems: "center",
    },
    premiumRingGradient: {
      width: "100%",
      height: "100%",
      borderRadius: 230,
    },

    userName: {
      fontSize: 30,
      fontWeight: "700",
      color: colors.textPrimary,
      marginTop: 30,
    },
    roleBadge: {
      backgroundColor: colors.roleBadgeBg,
      paddingHorizontal: 14,
      paddingVertical: 4,
      borderRadius: 16,
      marginTop: 4,
    },
    roleText: {
      color: colors.roleBadgeText,
      fontWeight: "600",
      fontSize: 18,
    },

    // Form
    formCard: {
      width: "100%",
      backgroundColor: colors.cardBackground,
      borderRadius: 16,
      padding: 18,
      elevation: 2,
      shadowOpacity: theme === "dark" ? 0.3 : 0.1,
      shadowColor: colors.bankCardShadow,
      marginRight: 30,
      borderWidth: theme === "dark" ? 1 : 0,
      borderColor: colors.borderBlue,
    },
    inputLabel: {
      fontSize: 14,
      color: colors.primaryBlue,
      fontWeight: "600",
      marginTop: 10,
      marginBottom: 6,
    },
    input: {
      backgroundColor: colors.inputBackground,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 10,
      fontSize: 15,
      color: colors.textPrimary,
    },
    disabledInput: {
      backgroundColor: colors.disabledBackground,
      color: colors.disabledText,
    },

    saveButton: {
      marginTop: 10,
      padding: 15,
      borderRadius: 14,
      width: "100%",
      alignItems: "center",
    },
    saveText: {
      color: "#FFFFFF",
      fontSize: 16,
      fontWeight: "600",
    },

    centerContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: colors.background,
    },
    errorText: {
      color: colors.textSecondary,
      fontSize: 16,
    },

    // Bank Account Section
    bankAccountSection: {
      marginTop: 20,
      paddingTop: 20,
      borderTopWidth: 1,
      borderTopColor: colors.sectionBorder,
    },
    bankAccountHeaderRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 12,
    },

    // Enhanced Add Bank Button
    addBankButtonWrapper: {
      borderRadius: 12,
      overflow: "hidden",
      shadowColor: "#3B82F6",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 6,
    },
    addBankButton: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 12,
      gap: 8,
    },
    addBankIconWrapper: {
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: "rgba(255,255,255,0.25)",
      justifyContent: "center",
      alignItems: "center",
    },
    addBankIcon: {
      color: "#FFFFFF",
      fontSize: 16,
      fontWeight: "700",
    },
    addBankButtonText: {
      color: "#FFFFFF",
      fontSize: 14,
      fontWeight: "700",
      letterSpacing: 0.3,
    },

    bankAccountsList: {
      gap: 12,
    },
    bankAccountCard: {
      backgroundColor: colors.cardBackground,
      borderWidth: 2,
      borderColor: colors.bankCardBorder,
      borderRadius: 16,
      padding: 10,
      flexDirection: "row",
      alignItems: "center",
      gap: 14,
      shadowColor: colors.bankCardShadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: theme === "dark" ? 0.3 : 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    bankAccountLogo: {
      width: 56,
      height: 56,
      borderRadius: 12,
      backgroundColor: "#FFFFFF",
      borderWidth: 2,
      borderColor: colors.sectionBorder,
    },
    bankAccountInfo: {
      flex: 1,
    },
    bankAccountHeader: {
      marginBottom: 4,
    },
    bankName: {
      fontSize: 17,
      fontWeight: "800",
      color: colors.textPrimary,
      lineHeight: 20,
    },
    bankNameSeparator: {
      fontWeight: "400",
      color: colors.textMuted,
    },
    bankFullNameText: {
      fontSize: 14,
      fontWeight: "500",
      color: colors.textSecondary,
    },
    accountDetails: {
      gap: 2,
    },
    accountRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 2,
    },
    accountLabel: {
      fontSize: 12,
      fontWeight: "600",
      color: colors.textMuted,
      minWidth: 55,
    },
    accountNumber: {
      fontSize: 15,
      color: colors.accentBlue,
      fontWeight: "700",
      letterSpacing: 0.5,
    },
    accountHolder: {
      fontSize: 14,
      color: colors.textPrimary,
      fontWeight: "600",
    },
    defaultBadge: {
      backgroundColor: colors.defaultBadgeBg,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 20,
      shadowColor: colors.defaultBadgeBg,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
      elevation: 2,
    },
    defaultText: {
      color: "#FFFFFF",
      fontSize: 12,
      fontWeight: "800",
    },
    noBankText: {
      fontSize: 14,
      color: colors.textMuted,
      fontStyle: "italic",
      textAlign: "center",
      paddingVertical: 20,
    },

    // Modal Styles
    modalOverlay: {
      flex: 1,
      backgroundColor: colors.modalOverlay,
      justifyContent: "center",
      alignItems: "center",
      padding: 20,
    },
    modalContent: {
      backgroundColor: colors.modalBackground,
      borderRadius: 24,
      padding: 0,
      width: "100%",
      maxWidth: 550,
      maxHeight: "85%",
      shadowColor: "#000000",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.4,
      shadowRadius: 16,
      elevation: 12,
      overflow: "hidden",
      borderWidth: theme === "dark" ? 1 : 0,
      borderColor: colors.borderBlue,
    },
    modalHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingHorizontal: 24,
      paddingVertical: 20,
      backgroundColor: colors.accentBlue,
    },
    modalTitle: {
      fontSize: 24,
      fontWeight: "700",
      color: "#FFFFFF",
      flex: 1,
    },
    closeButton: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: "rgba(255, 255, 255, 0.2)",
      justifyContent: "center",
      alignItems: "center",
    },
    closeButtonText: {
      color: "#FFFFFF",
      fontSize: 20,
      fontWeight: "700",
    },
    searchInput: {
      backgroundColor: colors.searchInputBg,
      borderWidth: 1,
      borderColor: colors.searchInputBorder,
      borderRadius: 12,
      paddingHorizontal: 16,
      paddingVertical: 12,
      fontSize: 15,
      color: colors.textPrimary,
      marginHorizontal: 20,
      marginTop: 20,
      marginBottom: 12,
    },
    bankListContainer: {
      maxHeight: 300,
      marginHorizontal: 20,
      marginBottom: 12,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.searchInputBorder,
      backgroundColor: colors.cardBackground,
    },
    bankItem: {
      flexDirection: "row",
      alignItems: "center",
      padding: 14,
      borderBottomWidth: 1,
      borderBottomColor: colors.bankItemBorder,
      backgroundColor: colors.cardBackground,
    },
    bankItemSelected: {
      backgroundColor: colors.bankItemSelectedBg,
      borderLeftWidth: 4,
      borderLeftColor: colors.accentBlue,
    },
    bankLogo: {
      width: 48,
      height: 48,
      borderRadius: 8,
      backgroundColor: "#FFFFFF",
      marginRight: 12,
      borderWidth: 1,
      borderColor: colors.sectionBorder,
    },
    bankInfo: {
      flex: 1,
    },
    bankShortName: {
      fontSize: 16,
      fontWeight: "700",
      color: colors.textPrimary,
      marginBottom: 2,
    },
    bankFullName: {
      fontSize: 13,
      color: colors.textSecondary,
      lineHeight: 18,
    },
    checkmark: {
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: "#10B981",
      justifyContent: "center",
      alignItems: "center",
    },
    checkmarkText: {
      color: "#FFFFFF",
      fontSize: 14,
      fontWeight: "700",
    },
    modalButtons: {
      flexDirection: "row",
      gap: 12,
      marginTop: 24,
      paddingHorizontal: 20,
      paddingBottom: 20,
    },
    cancelButton: {
      flex: 1,
      backgroundColor: colors.cancelButtonBg,
      paddingVertical: 14,
      borderRadius: 12,
      alignItems: "center",
      borderWidth: 1,
      borderColor: colors.cancelButtonBorder,
    },
    cancelButtonText: {
      color: colors.cancelButtonText,
      fontSize: 16,
      fontWeight: "700",
    },
    submitButton: {
      flex: 1,
      backgroundColor: colors.accentBlue,
      paddingVertical: 14,
      borderRadius: 12,
      alignItems: "center",
      shadowColor: colors.accentBlue,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 4,
    },
    submitButtonText: {
      color: "#FFFFFF",
      fontSize: 16,
      fontWeight: "700",
    },
    modalInputLabel: {
      fontSize: 14,
      color: colors.primaryBlue,
      fontWeight: "600",
      marginTop: 10,
      marginBottom: 6,
      marginHorizontal: 20,
    },
    modalInput: {
      backgroundColor: colors.inputBackground,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 10,
      fontSize: 15,
      color: colors.textPrimary,
      marginHorizontal: 20,
    },
  });
};

export default getStyles;
