import { StyleSheet, Dimensions } from "react-native";

const { width: SCREEN_WIDTH } = Dimensions.get("window");

// Light theme colors
const lightColors = {
    background: "#F8FAFC",
    headerBackground: "rgba(255,255,255,0.96)",
    headerTitle: "#084F8C",
    textPrimary: "#0F172A",
    textSecondary: "#475569",
    textMuted: "#94A3B8",
    cardBackground: "#FFFFFF",
    borderColor: "#E2E8F0",
    shadowColor: "#000",
    iconColor: "#084F8C",
    notificationBadgeBg: "#EF4444",
    notificationBadgeBorder: "#FFFFFF",
    walletLabel: "#475569",
    walletAmount: "#084F8C",
    walletIconBg: "rgba(8, 79, 140, 0.15)",
    walletDivider: "rgba(8, 79, 140, 0.2)",
    statLabel: "#64748B",
    statNumber: "#0F172A",
    statBorder: "#E0E7FF",
    actionCardBg: "#FFFFFF",
    actionCardBorder: "#E2E8F0",
    actionText: "#1E293B",
    topTemplateName: "#1E293B",
    topTemplateMeta: "#64748B",
    topTemplateRevenue: "#4F46E5",
    topTemplateChipBg: "#EEF2FF",
    sectionTitle: "#1E293B",
    notificationDropdownBg: "#FFFFFF",
    notificationText: "#111827",
    notificationSubText: "#6B7280",
    notificationReadBg: "#F9FAFB",
    notificationUnreadBg: "#DBEAFE",
};

// Dark theme colors
const darkColors = {
    background: "#0F172A",
    headerBackground: "rgba(30,41,59,0.96)",
    headerTitle: "#FFFFFF",
    textPrimary: "#F1F5F9",
    textSecondary: "#94A3B8",
    textMuted: "#64748B",
    cardBackground: "#1E293B",
    borderColor: "#334155",
    shadowColor: "#000",
    iconColor: "#FFFFFF",
    notificationBadgeBg: "#EF4444",
    notificationBadgeBorder: "#1E293B",
    walletLabel: "#94A3B8",
    walletAmount: "#084F8C", // Keep blue for contrast on light card
    walletIconBg: "rgba(8, 79, 140, 0.15)",
    walletDivider: "rgba(8, 79, 140, 0.2)",
    statLabel: "#94A3B8",
    statNumber: "#F1F5F9",
    statBorder: "#334155",
    actionCardBg: "#1E293B",
    actionCardBorder: "#334155",
    actionText: "#F1F5F9",
    topTemplateName: "#F1F5F9",
    topTemplateMeta: "#94A3B8",
    topTemplateRevenue: "#818CF8",
    topTemplateChipBg: "#312E81",
    sectionTitle: "#F1F5F9",
    notificationDropdownBg: "#1E293B",
    notificationText: "#F1F5F9",
    notificationSubText: "#94A3B8",
    notificationReadBg: "#1E293B",
    notificationUnreadBg: "#1E3A5F",
};

export const getStyles = (theme = "light") => {
    const colors = theme === "dark" ? darkColors : lightColors;

    return StyleSheet.create({
        container: {
            flex: 1,
            backgroundColor: colors.background,
        },
        header: {
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "space-between",
            paddingHorizontal: 20,
            paddingVertical: 16,
            backgroundColor: colors.headerBackground,
            borderBottomWidth: 1,
            borderBottomColor: colors.borderColor,
            shadowColor: colors.shadowColor,
            shadowOpacity: theme === "dark" ? 0.3 : 0.06,
            shadowRadius: 8,
            elevation: 4,
            paddingTop: 40,
        },
        headerLeft: {
            flexDirection: "row",
            alignItems: "center",
            gap: 15,
            flex: 1,
        },
        headerTitle: {
            fontSize: 26,
            fontFamily: "Pacifico-Regular",
            color: colors.headerTitle,
            letterSpacing: -0.5,
        },
        notificationButton: {
            width: 44,
            height: 44,
            alignItems: "center",
            justifyContent: "center",
            position: "relative",
            borderRadius: 22,
            backgroundColor: colors.cardBackground,
            shadowColor: colors.shadowColor,
            shadowOpacity: theme === "dark" ? 0.3 : 0.05,
            shadowRadius: 6,
            elevation: 3,
        },
        notificationBadge: {
            position: "absolute",
            top: 10,
            right: 10,
            width: 10,
            height: 10,
            borderRadius: 5,
            backgroundColor: colors.notificationBadgeBg,
            borderWidth: 2,
            borderColor: colors.notificationBadgeBorder,
        },
        content: {
            flex: 1,
        },
        heroBackground: {
            width: "100%",
            height: 260,
            marginBottom: 20,
            overflow: "hidden",
        },
        heroOverlay: {
            ...StyleSheet.absoluteFillObject,
            backgroundColor: "rgba(6, 40, 71, 0.19)",
        },
        heroContent: {
            flex: 1,
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "flex-start",
            paddingHorizontal: 24,
            paddingTop: 20,
        },
        greetingColumn: {
            flex: 1,
            paddingRight: 20,
        },
        greetingText: {
            fontSize: 34,
            fontWeight: "800",
            color: "#FFFFFF",
            letterSpacing: -0.5,
            textShadowColor: "#000",
            textShadowOffset: { width: 1, height: 2 },
            textShadowRadius: 4,
        },
        subGreetingText: {
            fontSize: 16,
            color: "#E0E7FF",
            marginTop: 6,
            fontWeight: "500",
            textShadowColor: "#000",
            textShadowOffset: { width: 1, height: 2 },
            textShadowRadius: 4,
        },
        walletCard: {
            width: 280,
            borderRadius: 24,
            overflow: "hidden",
            shadowColor: colors.shadowColor,
            shadowOffset: { width: 0, height: 8 },
            shadowOpacity: 0.2,
            shadowRadius: 20,
            elevation: 12,
        },
        walletGradient: {
            padding: 18,
        },
        walletHeaderRow: {
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "flex-start",
            marginBottom: 16,
        },
        walletLabel: {
            fontSize: 13,
            color: colors.walletLabel,
            fontWeight: "600",
            marginBottom: 4,
        },
        walletAmount: {
            fontSize: 28,
            fontWeight: "800",
            color: colors.walletAmount,
            letterSpacing: -0.5,
        },
        walletIconBg: {
            width: 52,
            height: 52,
            borderRadius: 26,
            backgroundColor: colors.walletIconBg,
            alignItems: "center",
            justifyContent: "center",
        },
        walletDivider: {
            height: 1,
            backgroundColor: colors.walletDivider,
            marginVertical: 12,
        },
        walletFooterRow: {
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "center",
        },
        walletFooterText: {
            fontSize: 15,
            fontWeight: "600",
            color: "#084F8C",
        },
        statsGrid: {
            flexDirection: "row",
            paddingHorizontal: 20,
            marginBottom: 24,
            gap: 12,
        },
        statCard: {
            flex: 1,
            backgroundColor: colors.cardBackground,
            borderRadius: 20,
            padding: 12,
            borderWidth: 2,
            borderColor: colors.statBorder,
            shadowColor: "#084F8C",
            shadowOpacity: theme === "dark" ? 0.2 : 0.08,
            shadowRadius: 12,
            elevation: 4,
        },
        statContent: {
            flex: 1,
            justifyContent: 'space-between',
        },
        statHeader: {
            marginBottom: 12,
        },
        statLabel: {
            fontSize: 13,
            color: colors.statLabel,
            fontWeight: "600",
            marginBottom: 4,
        },
        statNumber: {
            fontSize: 22,
            fontWeight: "700",
            color: colors.statNumber,
        },
        statIllustration: {
            width: "100%",
            height: 160,
            borderRadius: 12,
        },
        section: {
            marginBottom: 24,
            paddingHorizontal: 20,
        },
        sectionTitle: {
            fontSize: 18,
            fontWeight: "700",
            color: colors.sectionTitle,
            marginBottom: 16,
        },
        actionsGrid: {
            flexDirection: "row",
            flexWrap: "wrap",
            gap: 12,
        },
        actionCard: {
            width: (SCREEN_WIDTH - 40 - 12) / 2,
            backgroundColor: colors.actionCardBg,
            borderRadius: 16,
            padding: 16,
            borderWidth: 1,
            borderColor: colors.actionCardBorder,
            alignItems: "center",
            justifyContent: "center",
            shadowColor: colors.shadowColor,
            shadowOpacity: theme === "dark" ? 0.2 : 0.05,
            shadowRadius: 8,
            elevation: 2,
        },
        actionIcon: {
            width: 48,
            height: 48,
            borderRadius: 24,
            alignItems: "center",
            justifyContent: "center",
            marginBottom: 12,
        },
        actionText: {
            fontSize: 14,
            fontWeight: "600",
            color: colors.actionText,
        },
        topTemplateList: {
            gap: 12,
        },
        topTemplateCard: {
            flexDirection: "row",
            alignItems: "center",
            backgroundColor: colors.cardBackground,
            borderRadius: 16,
            padding: 12,
            borderWidth: 1,
            borderColor: colors.borderColor,
        },
        topTemplateRow: {
            flexDirection: "row",
            alignItems: "center",
            flex: 1,
            gap: 12,
        },
        topTemplateThumbnail: {
            width: 48,
            height: 48,
            borderRadius: 10,
            backgroundColor: "#EFF6FF",
            alignItems: "center",
            justifyContent: "center",
        },
        topTemplateName: {
            fontSize: 15,
            fontWeight: "600",
            color: colors.topTemplateName,
            marginBottom: 4,
        },
        topTemplateMeta: {
            fontSize: 12,
            color: colors.topTemplateMeta,
        },
        topTemplateChip: {
            flexDirection: "row",
            alignItems: "center",
            gap: 4,
            paddingHorizontal: 8,
            paddingVertical: 4,
            borderRadius: 8,
            backgroundColor: colors.topTemplateChipBg,
        },
        topTemplateRevenueValue: {
            fontSize: 13,
            fontWeight: "700",
            color: colors.topTemplateRevenue,
        },
        activityTime: {
            fontSize: 14,
            color: colors.textMuted,
            textAlign: "center",
            marginTop: 10,
        },

        // Notification Dropdown
        notificationDropdown: {
            position: "absolute",
            top: 80,
            right: 20,
            width: 320,
            maxHeight: 360,
            backgroundColor: colors.notificationDropdownBg,
            borderRadius: 16,
            paddingVertical: 8,
            paddingHorizontal: 12,
            shadowColor: colors.shadowColor,
            shadowOpacity: 0.15,
            shadowRadius: 12,
            shadowOffset: { width: 0, height: 6 },
            elevation: 8,
            zIndex: 50,
        },
        notificationHeader: {
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "space-between",
            marginBottom: 8,
        },
        notificationTitle: {
            fontSize: 16,
            fontWeight: "700",
            color: colors.notificationText,
        },
        notificationMetaRow: {
            flexDirection: "row",
            alignItems: "center",
            gap: 8,
        },
        notificationUnreadText: {
            fontSize: 12,
            color: colors.notificationSubText,
        },
        markAllReadText: {
            fontSize: 12,
            color: "#2563EB",
            fontWeight: "600",
        },
        loadingContainer: {
            alignItems: "center",
            justifyContent: "center",
            paddingVertical: 20,
        },
        loadingText: {
            color: colors.notificationSubText,
        },
        emptyNotificationContainer: {
            alignItems: "center",
            justifyContent: "center",
            paddingVertical: 16,
        },
        emptyNotificationText: {
            marginTop: 6,
            color: colors.notificationSubText,
            fontSize: 13,
        },
        notificationItem: {
            paddingVertical: 8,
            paddingHorizontal: 8,
            borderRadius: 10,
            marginBottom: 4,
        },
        notificationItemRead: {
            backgroundColor: colors.notificationReadBg,
        },
        notificationItemUnread: {
            backgroundColor: colors.notificationUnreadBg,
        },
        notificationItemTitle: {
            fontSize: 14,
            fontWeight: "700",
            color: colors.notificationText,
            marginBottom: 2,
        },
        notificationItemMessage: {
            fontSize: 13,
            color: colors.notificationSubText,
            marginBottom: 2,
        },
        notificationItemTime: {
            fontSize: 11,
            color: colors.notificationSubText,
            marginTop: 2,
        },

        // Colors for inline use
        iconColor: colors.iconColor,
        primaryBlue: "#084F8C", // Keep fixed for some elements
    });
};
