import { StyleSheet } from "react-native";

const lightColors = {
    background: "#F1F5F9",
    headerBg: "#FFFFFF",
    headerBorder: "#E2E8F0",
    headerTitle: "#084F8C",
    headerSubtitle: "#64748B",
    cardBg: "#FFFFFF",
    cardShadow: "#000",
    cardTitle: "#1E293B",
    inputBg: "#F8FAFC",
    inputBorder: "#E2E8F0",
    inputText: "#0F172A",
    inputPlaceholder: "#94A3B8",
    charCount: "#94A3B8",
    gridLabel: "#475569",
    imageCardBg: "#F8FAFC",
    imageCardBorder: "#E2E8F0",
    iconCircleBg: "#EFF6FF",
    emptyLabel: "#334155",
    emptyHint: "#94A3B8",
    tipsBg: "#FFFBEB",
    tipsBorder: "#FEF3C7",
    tipsText: "#92400E",
    footerBg: "#FFFFFF",
    footerBorder: "#E2E8F0",
    iconColor: "#3B82F6",
    backButtonIcon: "#084F8C",
};

const darkColors = {
    background: "#0F172A",
    headerBg: "#1E293B",
    headerBorder: "#334155",
    headerTitle: "#FFFFFF",
    headerSubtitle: "#94A3B8",
    cardBg: "#1E293B",
    cardShadow: "#000",
    cardTitle: "#F1F5F9",
    inputBg: "#334155",
    inputBorder: "#475569",
    inputText: "#F1F5F9",
    inputPlaceholder: "#94A3B8",
    charCount: "#64748B",
    gridLabel: "#CBD5E1",
    imageCardBg: "#334155",
    imageCardBorder: "#475569",
    iconCircleBg: "#1E293B",
    emptyLabel: "#E2E8F0",
    emptyHint: "#94A3B8",
    tipsBg: "#422006",
    tipsBorder: "#713F12",
    tipsText: "#FEF3C7",
    footerBg: "#1E293B",
    footerBorder: "#334155",
    iconColor: "#60A5FA",
    backButtonIcon: "#F1F5F9",
};

export const getStyles = (theme = "light") => {
    const colors = theme === "dark" ? darkColors : lightColors;

    return StyleSheet.create({
        container: {
            flex: 1,
            backgroundColor: colors.background,
        },
        header: {
            backgroundColor: colors.headerBg,
            borderBottomWidth: 1,
            borderBottomColor: colors.headerBorder,
            shadowColor: "#000",
            shadowOffset: { width: 0, height: 1 },
            shadowOpacity: 0.05,
            shadowRadius: 3,
            elevation: 2,
        },
        headerContent: {
            flexDirection: "row",
            alignItems: "center",
            paddingHorizontal: 20,
            paddingVertical: 16,
            gap: 12,
        },
        headerTextContainer: {
            flex: 1,
        },
        headerTitle: {
            fontSize: 26,
            fontFamily: "Pacifico-Regular",
            color: colors.headerTitle,
            letterSpacing: -0.5,
        },
        headerSubtitle: {
            fontSize: 13,
            color: colors.headerSubtitle,
            marginTop: 2,
        },
        scrollView: {
            flex: 1,
        },
        scrollContent: {
            padding: 16,
            paddingBottom: 24,
        },
        card: {
            backgroundColor: colors.cardBg,
            borderRadius: 16,
            padding: 20,
            marginBottom: 16,
            shadowColor: colors.cardShadow,
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.04,
            shadowRadius: 8,
            elevation: 2,
        },
        cardHeader: {
            flexDirection: "row",
            alignItems: "center",
            gap: 8,
            marginBottom: 16,
        },
        cardTitle: {
            fontSize: 16,
            fontWeight: "600",
            color: colors.cardTitle,
        },
        titleInput: {
            backgroundColor: colors.inputBg,
            borderWidth: 1.5,
            borderColor: colors.inputBorder,
            borderRadius: 12,
            paddingHorizontal: 16,
            paddingVertical: 14,
            fontSize: 16,
            color: colors.inputText,
            fontWeight: "500",
        },
        charCount: {
            fontSize: 12,
            color: colors.charCount,
            marginTop: 8,
            textAlign: "right",
        },
        imagesGrid: {
            flexDirection: "row",
            gap: 12,
        },
        gridItem: {
            flex: 1,
        },
        gridLabel: {
            fontSize: 13,
            fontWeight: "600",
            color: colors.gridLabel,
            marginBottom: 8,
        },
        imageCard: {
            height: 165,
            borderRadius: 12,
            overflow: "hidden",
            backgroundColor: colors.imageCardBg,
            borderWidth: 2,
            borderColor: colors.imageCardBorder,
        },
        imageContainer: {
            flex: 1,
            position: "relative",
        },
        selectedImage: {
            width: "100%",
            height: "100%",
            resizeMode: "cover",
        },
        imageOverlay: {
            position: "absolute",
            bottom: 0,
            left: 0,
            right: 0,
            backgroundColor: "rgba(0,0,0,0.6)",
            paddingVertical: 8,
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "center",
            gap: 6,
        },
        overlayText: {
            color: "#FFF",
            fontSize: 12,
            fontWeight: "600",
        },
        emptyImageCard: {
            flex: 1,
            justifyContent: "center",
            alignItems: "center",
            padding: 16,
        },
        iconCircle: {
            width: 56,
            height: 56,
            borderRadius: 28,
            backgroundColor: colors.iconCircleBg,
            justifyContent: "center",
            alignItems: "center",
            marginBottom: 12,
        },
        emptyLabel: {
            fontSize: 14,
            fontWeight: "600",
            color: colors.emptyLabel,
            marginBottom: 4,
        },
        emptyHint: {
            fontSize: 12,
            color: colors.emptyHint,
        },
        tipsCard: {
            backgroundColor: colors.tipsBg,
            borderRadius: 12,
            padding: 16,
            flexDirection: "row",
            gap: 12,
            borderWidth: 1,
            borderColor: colors.tipsBorder,
        },
        tipsText: {
            flex: 1,
            fontSize: 13,
            color: colors.tipsText,
            lineHeight: 20,
        },
        tipsBold: {
            fontWeight: "700",
        },
        footer: {
            backgroundColor: colors.footerBg,
            borderTopWidth: 1,
            borderTopColor: colors.footerBorder,
            padding: 16,
            paddingBottom: 20,
        },
        createButton: {
            borderRadius: 14,
            overflow: "hidden",
            shadowColor: "#3B82F6",
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.3,
            shadowRadius: 12,
            elevation: 6,
            width: "30%",
            alignSelf: "center",
        },
        gradient: {
            paddingVertical: 16,
            paddingHorizontal: 24,
        },
        buttonContent: {
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "center",
            gap: 10,
        },
        loadingContainer: {
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "center",
            gap: 12,
        },
        buttonText: {
            color: "#FFFFFF",
            fontSize: 16,
            fontWeight: "700",
            letterSpacing: 0.3,
        },
        colors: colors,
    });
};
