import { StyleSheet } from "react-native";

const lightColors = {
    background: "#F0F9FF",
    headerBg: "#FFFFFF",
    headerBorder: "#E2E8F0",
    headerTitle: "#084F8C",
    headerIcon: "#084F8C",
    createButtonBg: ["#1863dbff", "#084F8C"],
    createButtonDisabled: ["#94a3b8", "#64748b"],
    createButtonText: "#ffffff",
    columnBg: "#FFFFFF",
    columnShadow: "#000",
    tabBg: "#F8FAFC",
    tabActiveBg: "#EFF6FF",
    tabBorderActive: "#3b82f6",
    tabText: "#64748b",
    tabTextActive: "#3b82f6",
    previewBorder: "#E2E8F0",
    previewLine: "rgba(0,0,0,0.1)",
    previewLabel: "#64748b",
    inputBg: "#F8FAFC",
    inputBorder: "#E2E8F0",
    inputText: "#0f172a",
    inputPlaceholder: "#94a3b8",
    label: "#475569",
    toggleBg: "#E2E8F0",
    toggleActiveBg: "#085497ff",
    toggleThumb: "#ffffff",
    orientationTabBg: "#F8FAFC",
    orientationTabBorder: "#E2E8F0",
    orientationTabActiveBg: "#EFF6FF",
    orientationTabActiveBorder: "#3b82f6",
    orientationIcon: "#64748b",
    orientationIconActive: "#3b82f6",
    sizeButtonBg: "#F8FAFC",
    sizeButtonBorder: "#E2E8F0",
    sizeButtonActiveBg: "#1366aeff",
    sizeButtonActiveBorder: "#084F8C",
    sizeButtonText: "#64748b",
    sizeButtonTextActive: "#ffffff",
    categoryPillBg: "#FFFFFF",
    categoryPillBorder: "#E2E8F0",
    categoryPillText: "#475569",
    categoryLine: "#E2E8F0",
    categoryTitle: "#0f172a",
    cardBg: "#FFFFFF",
    cardBorder: "#E2E8F0",
    cardActiveBg: "#EFF6FF",
    cardActiveBorder: "#3b82f6",
    cardIcon: "#94a3b8",
    cardText: "#64748b",
    loadingText: "#64748b",
    loadingIndicator: "#1863dbff",
    modalOverlay: "rgba(0,0,0,0.4)",
    modalBg: "#FFFFFF",
    modalTitle: "#111827",
    modalText: "#374151",
    modalButtonBg: "#3B82F6",
    modalButtonText: "#FFFFFF",
};

const darkColors = {
    background: "#0F172A",
    headerBg: "#1E293B",
    headerBorder: "#334155",
    headerTitle: "#FFFFFF",
    headerIcon: "#F1F5F9",
    createButtonBg: ["#3B82F6", "#2563EB"],
    createButtonDisabled: ["#475569", "#334155"],
    createButtonText: "#ffffff",
    columnBg: "#1E293B",
    columnShadow: "#000",
    tabBg: "#334155",
    tabActiveBg: "#1E40AF",
    tabBorderActive: "#60A5FA",
    tabText: "#94A3B8",
    tabTextActive: "#60A5FA",
    previewBorder: "#334155",
    previewLine: "rgba(255,255,255,0.1)",
    previewLabel: "#94A3B8",
    inputBg: "#334155",
    inputBorder: "#475569",
    inputText: "#F1F5F9",
    inputPlaceholder: "#94A3B8",
    label: "#CBD5E1",
    toggleBg: "#475569",
    toggleActiveBg: "#3B82F6",
    toggleThumb: "#F1F5F9",
    orientationTabBg: "#334155",
    orientationTabBorder: "#475569",
    orientationTabActiveBg: "#1E40AF",
    orientationTabActiveBorder: "#60A5FA",
    orientationIcon: "#94A3B8",
    orientationIconActive: "#60A5FA",
    sizeButtonBg: "#334155",
    sizeButtonBorder: "#475569",
    sizeButtonActiveBg: "#3B82F6",
    sizeButtonActiveBorder: "#60A5FA",
    sizeButtonText: "#94A3B8",
    sizeButtonTextActive: "#ffffff",
    categoryPillBg: "#1E293B",
    categoryPillBorder: "#334155",
    categoryPillText: "#CBD5E1",
    categoryLine: "#334155",
    categoryTitle: "#F1F5F9",
    cardBg: "#1E293B",
    cardBorder: "#334155",
    cardActiveBg: "#1E40AF",
    cardActiveBorder: "#60A5FA",
    cardIcon: "#94A3B8",
    cardText: "#94A3B8",
    loadingText: "#94A3B8",
    loadingIndicator: "#60A5FA",
    modalOverlay: "rgba(0,0,0,0.7)",
    modalBg: "#1E293B",
    modalTitle: "#F1F5F9",
    modalText: "#CBD5E1",
    modalButtonBg: "#3B82F6",
    modalButtonText: "#FFFFFF",
};

export const getStyles = (theme = "light") => {
    const colors = theme === "dark" ? darkColors : lightColors;

    return StyleSheet.create({
        container: {
            flex: 1,
            backgroundColor: colors.background,
        },
        header: {
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "space-between",
            paddingHorizontal: 20,
            paddingVertical: 16,
            backgroundColor: colors.headerBg,
            borderBottomWidth: 1,
            borderBottomColor: colors.headerBorder,
            shadowColor: "#000",
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.05,
            shadowRadius: 8,
            elevation: 2,
        },
        headerLeft: {
            flexDirection: "row",
            alignItems: "center",
            gap: 15,
            flex: 1,
        },
        headerTitle: {
            fontSize: 26,
            fontFamily: "Pacifico-Regular",
            color: colors.headerTitle,
            letterSpacing: -0.5,
        },
        createButton: {
            paddingHorizontal: 20,
            paddingVertical: 8,
            borderRadius: 8,
        },
        createButtonText: {
            fontSize: 16,
            fontWeight: "600",
            color: colors.createButtonText,
        },
        content: {
            flex: 1,
        },
        topSection: {
            flexDirection: "row",
            padding: 20,
            paddingTop: 30,
            gap: 20,
        },
        leftColumn: {
            flex: 1,
            backgroundColor: colors.columnBg,
            borderRadius: 16,
            padding: 20,
            shadowColor: colors.columnShadow,
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.05,
            shadowRadius: 8,
            elevation: 2,
        },
        rightColumn: {
            flex: 1,
            backgroundColor: colors.columnBg,
            borderRadius: 16,
            padding: 20,
            shadowColor: colors.columnShadow,
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.05,
            shadowRadius: 8,
            elevation: 2,
            gap: 16,
        },
        tabContainer: {
            flexDirection: "row",
            gap: 12,
            marginBottom: 20,
        },
        tabButton: {
            flex: 1,
            alignItems: "center",
            padding: 12,
            backgroundColor: colors.tabBg,
            borderRadius: 12,
            borderWidth: 2,
            borderColor: "transparent",
        },
        tabButtonActive: {
            borderColor: colors.tabBorderActive,
            backgroundColor: colors.tabActiveBg,
        },
        tabLabel: {
            fontSize: 14,
            color: colors.tabText,
            fontWeight: "500",
        },
        tabLabelActive: {
            color: colors.tabTextActive,
            fontWeight: "600",
        },
        previewContainer: {
            flexDirection: "row",
            gap: 12,
        },
        previewCard: {
            flex: 1,
        },
        previewBox: {
            height: 180,
            borderRadius: 12,
            padding: 16,
            justifyContent: "flex-end",
            borderWidth: 1,
            borderColor: colors.previewBorder,
            overflow: "hidden",
        },
        previewPortrait: {
            height: 330,
        },
        previewLandscape: {
            height: 150,
        },
        previewBoxInner: {
            position: "absolute",
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
        },
        previewImage: {
            position: "absolute",
            top: 0,
            left: 15,
            right: 0,
            bottom: 0,
            width: "100%",
            height: "100%",
        },
        previewLines: {
            position: "absolute",
            top: 16,
            left: 16,
            right: 16,
            gap: 8,
        },
        previewLine: {
            height: 2,
            backgroundColor: colors.previewLine,
        },
        previewLabel: {
            fontSize: 12,
            color: colors.previewLabel,
            fontWeight: "500",
            marginBottom: -8,
        },
        titleInput: {
            backgroundColor: colors.inputBg,
            borderRadius: 12,
            padding: 14,
            fontSize: 16,
            color: colors.inputText,
            borderWidth: 1,
            borderColor: colors.inputBorder,
        },
        descriptionInput: {
            backgroundColor: colors.inputBg,
            borderRadius: 12,
            padding: 14,
            fontSize: 15,
            color: colors.inputText,
            borderWidth: 1,
            borderColor: colors.inputBorder,
            minHeight: 80,
        },
        settingRow: {
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "center",
        },
        settingColumn: {
            gap: 8,
        },
        settingLabel: {
            fontSize: 15,
            color: colors.label,
            fontWeight: "500",
        },
        toggle: {
            width: 50,
            height: 28,
            borderRadius: 14,
            backgroundColor: colors.toggleBg,
            padding: 2,
        },
        toggleActive: {
            backgroundColor: colors.toggleActiveBg,
        },
        toggleThumb: {
            width: 24,
            height: 24,
            borderRadius: 12,
            backgroundColor: colors.toggleThumb,
        },
        toggleThumbActive: {
            transform: [{ translateX: 22 }],
        },
        orientationTabs: {
            flexDirection: "row",
            gap: 8,
        },
        orientationTab: {
            flex: 1,
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "center",
            backgroundColor: colors.orientationTabBg,
            borderRadius: 12,
            paddingVertical: 10,
            borderWidth: 1,
            borderColor: colors.orientationTabBorder,
            gap: 8,
        },
        orientationTabActive: {
            backgroundColor: colors.orientationTabActiveBg,
            borderColor: colors.orientationTabActiveBorder,
        },
        orientationTabText: {
            fontSize: 14,
            color: colors.orientationIcon,
            fontWeight: "500",
        },
        orientationTabTextActive: {
            color: colors.orientationIconActive,
            fontWeight: "600",
        },
        sizeButtons: {
            flexDirection: "row",
            flexWrap: "wrap",
            gap: 8,
        },
        sizeButton: {
            paddingHorizontal: 16,
            paddingVertical: 8,
            borderRadius: 8,
            backgroundColor: colors.sizeButtonBg,
            borderWidth: 1,
            borderColor: colors.sizeButtonBorder,
        },
        sizeButtonActive: {
            backgroundColor: colors.sizeButtonActiveBg,
            borderColor: colors.sizeButtonActiveBorder,
        },
        sizeButtonText: {
            fontSize: 14,
            color: colors.sizeButtonText,
            fontWeight: "500",
        },
        sizeButtonTextActive: {
            color: colors.sizeButtonTextActive,
            fontWeight: "600",
        },
        bottomSection: {
            paddingHorizontal: 20,
        },
        categoryScroll: {
            marginBottom: 20,
        },
        categoryScrollContent: {
            gap: 12,
        },
        categoryPill: {
            paddingHorizontal: 20,
            paddingVertical: 10,
            backgroundColor: colors.categoryPillBg,
            borderRadius: 20,
            borderWidth: 1,
            borderColor: colors.categoryPillBorder,
            shadowColor: "#000",
            shadowOffset: { width: 0, height: 1 },
            shadowOpacity: 0.05,
            shadowRadius: 4,
            elevation: 1,
        },
        categoryPillText: {
            fontSize: 14,
            color: colors.categoryPillText,
            fontWeight: "600",
        },
        categoryHeader: {
            flexDirection: "row",
            alignItems: "center",
            marginVertical: 20,
            gap: 12,
        },
        categoryLine: {
            flex: 1,
            height: 1,
            backgroundColor: colors.categoryLine,
        },
        categoryTitle: {
            fontSize: 16,
            fontWeight: "600",
            color: colors.categoryTitle,
        },
        templatesGrid: {
            flexDirection: "row",
            flexWrap: "wrap",
            gap: 12,
            marginBottom: 20,
        },
        templateCard: {
            alignItems: "center",
            padding: 12,
            borderRadius: 12,
            backgroundColor: colors.cardBg,
            borderWidth: 2,
            borderColor: colors.cardBorder,
        },
        paperCardPortrait: {
            width: 140,
        },
        paperCardLandscape: {
            width: 200,
        },
        templateCardActive: {
            borderColor: colors.cardActiveBorder,
            backgroundColor: colors.cardActiveBg,
        },
        paperTemplatePreview: {
            width: "100%",
            height: 160,
            borderRadius: 8,
            backgroundColor: colors.inputBg,
            justifyContent: "center",
            alignItems: "center",
            marginBottom: 8,
            borderWidth: 1,
            borderColor: colors.cardBorder,
        },
        paperPreviewPortrait: {
            height: 160,
        },
        paperPreviewLandscape: {
            height: 120,
        },
        templateName: {
            fontSize: 13,
            color: colors.cardText,
            textAlign: "center",
        },
        horizontalTemplates: {
            paddingRight: 20,
            gap: 12,
            paddingBottom: 20,
        },
        coverTemplateCard: {
            alignItems: "center",
            padding: 10,
            borderRadius: 12,
            backgroundColor: colors.cardBg,
            borderWidth: 2,
            borderColor: colors.cardBorder,
        },
        coverCardPortrait: {
            width: 140,
        },
        coverCardLandscape: {
            width: 200,
        },
        coverTemplateCardActive: {
            borderColor: colors.cardActiveBorder,
            backgroundColor: colors.cardActiveBg,
        },
        coverTemplatePreview: {
            borderRadius: 8,
            marginBottom: 8,
            justifyContent: "center",
            alignItems: "center",
            borderWidth: 1,
            borderColor: colors.cardBorder,
        },
        coverPreviewPortrait: {
            width: 120,
            height: 180,
        },
        coverPreviewLandscape: {
            width: 180,
            height: 120,
        },
        coverEmoji: {
            fontSize: 48,
        },
        coverTemplateName: {
            fontSize: 11,
            color: colors.cardText,
            textAlign: "center",
            height: 32,
        },
        loadingContainer: {
            flex: 1,
            alignItems: "center",
            justifyContent: "center",
            paddingVertical: 60,
        },
        loadingText: {
            marginTop: 16,
            fontSize: 14,
            color: colors.loadingText,
        },
        emptyContainer: {
            flex: 1,
            alignItems: "center",
            justifyContent: "center",
            paddingVertical: 60,
        },
        emptyText: {
            marginTop: 12,
            fontSize: 14,
            color: colors.loadingText,
        },
        modalOverlay: {
            flex: 1,
            backgroundColor: colors.modalOverlay,
            justifyContent: "center",
            alignItems: "center",
            padding: 16,
        },
        modalContent: {
            width: 300,
            maxWidth: "95%",
            backgroundColor: colors.modalBg,
            borderRadius: 16,
            padding: 16,
        },
        modalTitle: {
            fontSize: 18,
            fontWeight: "700",
            color: colors.modalTitle,
            marginBottom: 12,
        },
        modalText: {
            fontSize: 14,
            color: colors.modalText,
            marginBottom: 16,
        },
        modalButton: {
            flex: 1,
            paddingVertical: 10,
            borderRadius: 10,
            alignItems: "center",
            backgroundColor: colors.modalButtonBg,
        },
        modalButtonText: {
            color: colors.modalButtonText,
            fontSize: 14,
            fontWeight: "600",
        },
        colors: colors,
    });
};
