import { StyleSheet, Dimensions } from "react-native";
const screenWidth = Dimensions.get("window").width;

const lightColors = {
    background: "#F8FAFC",
    headerBg: "#FFFFFF",
    headerBorder: "#E2E8F0",
    headerTitle: "#084F8C",
    backButtonBg: "#F8FAFC",
    backButtonShadow: "#000",
    tabBarBg: "#FFFFFF",
    tabText: "#64748B",
    tabTextActive: "#084F8C",
    tabIndicator: "#084F8C",
    cardBg: "#FFFFFF",
    cardBorder: "#E0E7FF",
    cardShadow: "#084F8C",
    cardTitle: "#1E293B",
    cardDescription: "#94A3B8",
    cardDate: "#64748B",
    emptyIcon: "#CBD5E1",
    emptyText: "#94A3B8",
    modalOverlay: "rgba(0,0,0,0.45)",
    modalBg: "#FFFFFF",
    modalBorder: "#E0E7FF",
    modalShadow: "#084F8C",
    modalHeaderBorder: "#E0E7FF",
    modalTitle: "#084F8C",
    modalCloseIcon: "#0F172A",
    modalLabel: "#64748B",
    modalAmount: "#1E293B",
    detailSectionBg: "#F8FAFF",
    detailBorder: "#E0E7FF",
    detailLabel: "#64748B",
    detailValue: "#1E293B",
    closeBtnBg: "#084F8C",
    closeBtnText: "#FFF",
    iconColor: "#084F8C",
    loadingColor: "#084F8C",
};

const darkColors = {
    background: "#0F172A",
    headerBg: "#1E293B",
    headerBorder: "#334155",
    headerTitle: "#FFFFFF",
    backButtonBg: "#334155",
    backButtonShadow: "#000",
    tabBarBg: "#1E293B",
    tabText: "#94A3B8",
    tabTextActive: "#60A5FA",
    tabIndicator: "#60A5FA",
    cardBg: "#1E293B",
    cardBorder: "#334155",
    cardShadow: "#000",
    cardTitle: "#F1F5F9",
    cardDescription: "#94A3B8",
    cardDate: "#64748B",
    emptyIcon: "#475569",
    emptyText: "#64748B",
    modalOverlay: "rgba(0,0,0,0.8)",
    modalBg: "#1E293B",
    modalBorder: "#334155",
    modalShadow: "#000",
    modalHeaderBorder: "#334155",
    modalTitle: "#FFFFFF",
    modalCloseIcon: "#94A3B8",
    modalLabel: "#94A3B8",
    modalAmount: "#F1F5F9",
    detailSectionBg: "#0F172A",
    detailBorder: "#334155",
    detailLabel: "#94A3B8",
    detailValue: "#F1F5F9",
    closeBtnBg: "#3B82F6",
    closeBtnText: "#FFF",
    iconColor: "#F1F5F9",
    loadingColor: "#60A5FA",
};

export const getStyles = (theme = "light") => {
    const colors = theme === "dark" ? darkColors : lightColors;

    return StyleSheet.create({
        container: {
            flex: 1,
            backgroundColor: colors.background,
        },
        header: {
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "space-between",
            paddingHorizontal: 20,
            paddingVertical: 16,
            backgroundColor: colors.headerBg,
            paddingTop: 10,
            borderBottomWidth: 1,
            borderBottomColor: colors.headerBorder,
            shadowColor: "#000",
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.05,
            shadowRadius: 8,
            elevation: 2,
        },
        headerLeft: {
            flexDirection: "row",
            alignItems: "center",
            gap: 15,
            flex: 1,
        },
        headerTitle: {
            fontSize: 26,
            fontFamily: "Pacifico-Regular",
            color: colors.headerTitle,
            letterSpacing: -0.5,
        },
        backButton: {
            padding: 12,
            borderRadius: 30,
            backgroundColor: colors.backButtonBg,
            shadowColor: colors.backButtonShadow,
            shadowOpacity: 0.05,
            shadowRadius: 6,
            elevation: 3,
        },
        tabBar: {
            flexDirection: "row",
            backgroundColor: colors.tabBarBg,
            borderRadius: 16,
            marginHorizontal: 20,
            marginTop: 20,
            marginBottom: 10,
            overflow: "hidden",
            elevation: 2,
        },
        tab: { flex: 1, paddingVertical: 12, alignItems: "center" },
        tabText: { fontSize: 14, color: colors.tabText, fontWeight: "600" },
        tabTextActive: { color: colors.tabTextActive },
        tabIndicator: {
            position: "absolute",
            bottom: 0,
            width: screenWidth / 3,
            height: 3,
            backgroundColor: colors.tabIndicator,
        },
        card: {
            flexDirection: "row",
            alignItems: "center",
            backgroundColor: colors.cardBg,
            borderRadius: 20,
            padding: 16,
            marginBottom: 12,
            shadowColor: colors.cardShadow,
            shadowOpacity: 0.12,
            shadowRadius: 20,
            elevation: 6,
            borderColor: colors.cardBorder,
            borderWidth: 1,
        },
        iconWrap: {
            width: 48,
            height: 48,
            borderRadius: 16,
            justifyContent: "center",
            alignItems: "center",
            marginRight: 12,
        },
        cardTitle: {
            fontSize: 15,
            fontWeight: "700",
            color: colors.cardTitle,
            marginBottom: 2,
        },
        cardDescription: { fontSize: 13, color: colors.cardDescription, marginBottom: 2 },
        cardDate: { fontSize: 12, color: colors.cardDate },
        amount: { fontSize: 15, fontWeight: "700" },
        emptyBox: {
            alignItems: "center",
            justifyContent: "center",
            paddingVertical: 40,
        },
        emptyText: { fontSize: 14, color: colors.emptyText, marginTop: 12 },
        modalOverlay: {
            flex: 1,
            backgroundColor: colors.modalOverlay,
            justifyContent: "flex-end",
        },
        modalContent: {
            backgroundColor: colors.modalBg,
            borderTopLeftRadius: 32,
            borderTopRightRadius: 32,
            padding: 24,
            maxHeight: "85%",
            shadowColor: colors.modalShadow,
            shadowOpacity: 0.15,
            shadowRadius: 25,
            elevation: 12,
            borderWidth: 1,
            borderColor: colors.modalBorder,
        },
        modalHeader: {
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "center",
            marginBottom: 20,
            borderBottomWidth: 1,
            borderBottomColor: colors.modalHeaderBorder,
            paddingBottom: 12,
        },
        modalTitle: { fontSize: 20, fontWeight: "800", color: colors.modalTitle },
        modalIconSection: {
            alignItems: "center",
            marginBottom: 24,
        },
        modalIcon: {
            width: 80,
            height: 80,
            borderRadius: 40,
            justifyContent: "center",
            alignItems: "center",
            marginBottom: 12,
        },
        modalLabel: {
            fontSize: 16,
            fontWeight: "600",
            color: colors.modalLabel,
            marginBottom: 8,
        },
        modalAmount: { fontSize: 28, fontWeight: "700", color: colors.modalAmount },
        detailSection: {
            backgroundColor: colors.detailSectionBg,
            borderRadius: 20,
            padding: 16,
            marginBottom: 16,
        },
        detailRow: {
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "center",
            paddingVertical: 12,
            borderBottomWidth: 1,
            borderBottomColor: colors.detailBorder,
        },
        detailLabel: { fontSize: 14, color: colors.detailLabel, fontWeight: "500" },
        detailValue: { fontSize: 14, color: colors.detailValue, fontWeight: "600" },
        closeBtn: {
            backgroundColor: colors.closeBtnBg,
            paddingVertical: 14,
            borderRadius: 16,
            alignItems: "center",
        },
        closeBtnText: { color: colors.closeBtnText, fontWeight: "700", fontSize: 16 },
        centerContainer: {
            flex: 1,
            justifyContent: "center",
            alignItems: "center",
        },
        colors: colors,
    });
};
