import { StyleSheet } from "react-native";

// Light theme colors
const lightColors = {
    background: "#FAFAFA",
    centerBackground: "#FAFAFA",
    emptyText: "#64748B",
    headerBackground: "#FFFFFF",
    headerTitle: "#084F8C",
    cartButtonBg: "#FFFFFF",
    cartBadgeBg: "#EF4444",
    cartBadgeText: "#FFF",
    cartBadgeBorder: "#FFF",
    designerInfoBg: "#FFF",
    designerAvatarBorder: "#E0E7FF",
    designerName: "#084F8C",
    designerEmail: "#64748B",
    statValue: "#1E293B",
    statLabel: "#64748B",
    sectionTitle: "#084F8C",
    productCount: "#64748B",
    productCardBg: "#FFF",
    productCardBorder: "#E2E8F0",
    productImageBg: "#F1F5F9",
    typeBadgeBg: "rgba(30, 41, 59, 0.85)",
    typeBadgeText: "#FFF",
    ownerBadgeBg: "rgba(255, 255, 255, 0.95)",
    ownerBadgeBorder: "#D1FAE5",
    ownerBadgeText: "#059669",
    productName: "#1E293B",
    productDescription: "#64748B",
    starFilled: "#FBBF24",
    starEmpty: "#CBD5E1",
    productPrice: "#1E293B",
    addButtonBg: "#084F8C",
    emptyProductsText: "#64748B",
    shadowColor: "#000",
    iconColor: "#1E40AF",
    cartIconColor: "#084F8C",
    statIconColor: "#3B82F6",
    emptyIconColor: "#D1D5DB",
};

// Dark theme colors
const darkColors = {
    background: "#0F172A",
    centerBackground: "#0F172A",
    emptyText: "#94A3B8",
    headerBackground: "#1E293B",
    headerTitle: "#FFFFFF",
    cartButtonBg: "#334155",
    cartBadgeBg: "#EF4444",
    cartBadgeText: "#FFF",
    cartBadgeBorder: "#1E293B",
    designerInfoBg: "#1E293B",
    designerAvatarBorder: "#334155",
    designerName: "#F1F5F9",
    designerEmail: "#94A3B8",
    statValue: "#F1F5F9",
    statLabel: "#94A3B8",
    sectionTitle: "#F1F5F9",
    productCount: "#94A3B8",
    productCardBg: "#1E293B",
    productCardBorder: "#334155",
    productImageBg: "#334155",
    typeBadgeBg: "rgba(15, 23, 42, 0.9)",
    typeBadgeText: "#F1F5F9",
    ownerBadgeBg: "rgba(30, 41, 59, 0.95)",
    ownerBadgeBorder: "#064E3B",
    ownerBadgeText: "#34D399",
    productName: "#F1F5F9",
    productDescription: "#94A3B8",
    starFilled: "#FBBF24",
    starEmpty: "#475569",
    productPrice: "#F1F5F9",
    addButtonBg: "#60A5FA",
    emptyProductsText: "#94A3B8",
    shadowColor: "#000",
    iconColor: "#F1F5F9",
    cartIconColor: "#F1F5F9",
    statIconColor: "#60A5FA",
    emptyIconColor: "#475569",
};

export const getStyles = (theme = "light") => {
    const colors = theme === "dark" ? darkColors : lightColors;

    return StyleSheet.create({
        container: {
            flex: 1,
            backgroundColor: colors.background,
        },
        centerContainer: {
            flex: 1,
            justifyContent: "center",
            alignItems: "center",
            backgroundColor: colors.centerBackground,
        },
        emptyText: {
            marginTop: 16,
            fontSize: 18,
            color: colors.emptyText,
            fontWeight: "600",
        },

        // Header
        header: {
            paddingTop: 30,
            paddingBottom: 20,
            backgroundColor: colors.headerBackground,
            shadowColor: colors.shadowColor,
            shadowOffset: { width: 0, height: 10 },
            shadowOpacity: theme === "dark" ? 0.3 : 0.1,
            shadowRadius: 20,
            elevation: 15,
            position: "relative",
            overflow: "hidden",
        },
        headerGradient: {
            ...StyleSheet.absoluteFillObject,
            backgroundColor: "#3B82F6",
            opacity: 0.05,
        },
        headerContent: {
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "center",
            paddingHorizontal: 20,
        },
        headerLeft: {
            flexDirection: "row",
            alignItems: "center",
            gap: 15,
            flex: 1,
        },
        headerTitle: {
            fontSize: 24,
            fontFamily: "Pacifico-Regular",
            color: colors.headerTitle,
            letterSpacing: -0.5,
        },
        cartButton: {
            width: 40,
            height: 40,
            borderRadius: 10,
            justifyContent: "center",
            alignItems: "center",
            backgroundColor: colors.cartButtonBg,
            shadowColor: colors.shadowColor,
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.2,
            shadowRadius: 6,
            elevation: 4,
        },
        cartBadge: {
            position: "absolute",
            top: -4,
            right: -4,
            backgroundColor: colors.cartBadgeBg,
            minWidth: 24,
            height: 24,
            borderRadius: 12,
            justifyContent: "center",
            alignItems: "center",
            borderWidth: 3,
            borderColor: colors.cartBadgeBorder,
        },
        cartBadgeText: {
            color: colors.cartBadgeText,
            fontWeight: "900",
            fontSize: 12,
        },

        // Designer Info Section
        designerInfoSection: {
            backgroundColor: colors.designerInfoBg,
            margin: 20,
            borderRadius: 24,
            padding: 24,
            shadowColor: colors.shadowColor,
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.1,
            shadowRadius: 12,
            elevation: 6,
        },
        designerHeader: {
            flexDirection: "row",
            alignItems: "center",
            gap: 20,
        },
        designerAvatar: {
            width: 100,
            height: 100,
            borderRadius: 50,
            borderWidth: 4,
            borderColor: colors.designerAvatarBorder,
        },
        designerDetails: {
            flex: 1,
        },
        designerName: {
            fontSize: 24,
            fontFamily: "Pacifico-Regular",
            color: colors.designerName,
            marginBottom: 4,
        },
        designerEmail: {
            fontSize: 14,
            color: colors.designerEmail,
            marginBottom: 12,
        },
        statsContainer: {
            flexDirection: "row",
            gap: 24,
            marginTop: 8,
        },
        statItem: {
            flexDirection: "row",
            alignItems: "center",
            gap: 6,
        },
        statValue: {
            fontSize: 18,
            fontWeight: "900",
            color: colors.statValue,
        },
        statLabel: {
            fontSize: 12,
            color: colors.statLabel,
            fontWeight: "600",
        },

        // Products Section
        productsSection: {
            paddingHorizontal: 20,
            marginBottom: 20,
        },
        sectionHeader: {
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "center",
            marginBottom: 16,
        },
        sectionTitle: {
            fontSize: 22,
            fontFamily: "Pacifico-Regular",
            color: colors.sectionTitle,
        },
        productCount: {
            fontSize: 14,
            color: colors.productCount,
            fontWeight: "600",
        },

        // Products Grid - 4 items per row
        productsGrid: {
            flexDirection: "row",
            flexWrap: "wrap",
            gap: 12,
        },

        // Product Card - 23.5% width for 4 items per row
        productCard: {
            width: "23.5%",
            backgroundColor: colors.productCardBg,
            borderRadius: 16,
            overflow: "hidden",
            borderWidth: 1,
            borderColor: colors.productCardBorder,
            shadowColor: colors.shadowColor,
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.08,
            shadowRadius: 8,
            elevation: 3,
        },
        productImageContainer: {
            height: 120,
            position: "relative",
            backgroundColor: colors.productImageBg,
        },
        productImage: {
            width: "100%",
            height: "100%",
        },
        typeBadge: {
            position: "absolute",
            top: 6,
            left: 6,
            backgroundColor: colors.typeBadgeBg,
            paddingHorizontal: 6,
            paddingVertical: 3,
            borderRadius: 6,
        },
        typeBadgeText: {
            color: colors.typeBadgeText,
            fontSize: 8,
            fontWeight: "800",
            letterSpacing: 0.3,
        },
        ownerBadge: {
            position: "absolute",
            top: 6,
            right: 6,
            backgroundColor: colors.ownerBadgeBg,
            paddingHorizontal: 6,
            paddingVertical: 3,
            borderRadius: 6,
            flexDirection: "row",
            alignItems: "center",
            gap: 2,
            borderWidth: 1,
            borderColor: colors.ownerBadgeBorder,
        },
        ownerBadgeText: {
            fontSize: 8,
            fontWeight: "800",
            color: colors.ownerBadgeText,
        },
        productInfo: {
            padding: 10,
        },
        productName: {
            fontSize: 13,
            fontWeight: "800",
            color: colors.productName,
            lineHeight: 18,
            marginBottom: 3,
        },
        productDescription: {
            fontSize: 11,
            color: colors.productDescription,
            marginBottom: 5,
        },
        ratingContainer: {
            flexDirection: "row",
            gap: 1,
            marginBottom: 6,
        },
        productFooter: {
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "center",
            marginTop: 3,
        },
        productPrice: {
            fontSize: 14,
            fontWeight: "900",
            color: colors.productPrice,
        },
        addButton: {
            width: 32,
            height: 32,
            borderRadius: 16,
            backgroundColor: colors.addButtonBg,
            justifyContent: "center",
            alignItems: "center",
            shadowColor: colors.shadowColor,
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.3,
            shadowRadius: 4,
            elevation: 4,
        },

        // Empty State
        emptyProducts: {
            alignItems: "center",
            justifyContent: "center",
            paddingVertical: 60,
        },
        emptyProductsText: {
            marginTop: 16,
            fontSize: 16,
            color: colors.emptyProductsText,
            fontWeight: "600",
        },

        // Colors for inline usage
        iconColor: colors.iconColor,
        cartIconColor: colors.cartIconColor,
        statIconColor: colors.statIconColor,
        emptyIconColor: colors.emptyIconColor,
        starFilled: colors.starFilled,
        starEmpty: colors.starEmpty,
    });
};
