import { StyleSheet, Dimensions } from "react-native";

const screenWidth = Dimensions.get("window").width;

// Light theme colors
const lightColors = {
  background: "#F8FAFC",
  cardBackground: "#FFFFFF",
  headerBackground: "rgba(255,255,255,0.96)",
  primaryBlue: "#084F8C",
  primaryWhite: "#084F8C",
  accentBlue: "#1E40AF",
  textPrimary: "#1E293B",
  textSecondary: "#64748B",
  textMuted: "#9CA3AF",
  borderColor: "#E2E8F0",
  inputBackground: "#F8FAFC",
  shadowColor: "#000",
  badgeBackground: "#d3dde6ff",
  badgeText: "#000000",
  removeButtonBg: "#FEF2F2",
  removeButtonBorder: "#FECACA",
  discountBackground: "#F0FDF4",
  discountBorder: "#BBF7D0",
  discountText: "#16A34A",
  modalOverlay: "rgba(0, 0, 0, 0.6)",
  modalBackground: "#FFFFFF",
  modalHeaderBg: "#FAFBFC",
  modalItemBg: "#F9FAFB",
  modalFooterBg: "#FAFBFC",
  priceBreakdownBg: "#F9FAFB",
  totalRowBg: "#EFF6FF",
  paymentMethodBg: "#F5F3FF",
  paymentMethodBorder: "#E9D5FF",
  iconContainerBg: "#DBEAFE",
  cancelButtonBg: "#FFFFFF",
  cancelButtonBorder: "#D1D5DB",
  confirmButtonBg: "#1E40AF",
};

// Dark theme colors
const darkColors = {
  background: "#0F172A",
  cardBackground: "#1E293B",
  headerBackground: "rgba(30,41,59,0.96)",
  primaryBlue: "#3B82F6",
  primaryWhite: "#FFFFFF",
  accentBlue: "#60A5FA",
  textPrimary: "#F1F5F9",
  textSecondary: "#94A3B8",
  textMuted: "#64748B",
  borderColor: "#334155",
  inputBackground: "#0F172A",
  shadowColor: "#000",
  badgeBackground: "#334155",
  badgeText: "#F1F5F9",
  removeButtonBg: "#450A0A",
  removeButtonBorder: "#7F1D1D",
  discountBackground: "#064E3B",
  discountBorder: "#10B981",
  discountText: "#34D399",
  modalOverlay: "rgba(0, 0, 0, 0.8)",
  modalBackground: "#1E293B",
  modalHeaderBg: "#0F172A",
  modalItemBg: "#0F172A",
  modalFooterBg: "#0F172A",
  priceBreakdownBg: "#0F172A",
  totalRowBg: "#1E3A5F",
  paymentMethodBg: "#2E1065",
  paymentMethodBorder: "#7C3AED",
  iconContainerBg: "#1E3A5F",
  cancelButtonBg: "#1E293B",
  cancelButtonBorder: "#475569",
  confirmButtonBg: "#3B82F6",
};

const getStyles = (theme = "light") => {
  const colors = theme === "dark" ? darkColors : lightColors;

  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },

    // Header
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 20,
      paddingTop: 16,
      paddingBottom: 16,
      backgroundColor: colors.headerBackground,
      borderBottomWidth: 1,
      borderBottomColor: colors.borderColor,
      shadowColor: colors.shadowColor,
      shadowOpacity: theme === "dark" ? 0.3 : 0.06,
      shadowRadius: 8,
      elevation: 4,
    },

    leftHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },

    backBtn: {
      padding: 12,
      borderRadius: 30,
      backgroundColor: colors.inputBackground,
      shadowColor: colors.shadowColor,
      shadowOpacity: 0.05,
      shadowRadius: 6,
      elevation: 3,
    },

    headerTitle: {
      fontSize: 26,
      fontFamily: "Pacifico-Regular",
      color: colors.primaryWhite,
      letterSpacing: -0.5,
    },

    continueText: {
      fontSize: 16,
      color: colors.primaryWhite,
      fontFamily: "Pacifico-Regular",
    },

    // Empty State
    emptyContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: 32,
    },
    emptyTitle: {
      fontSize: 26,
      fontWeight: "700",
      color: colors.textPrimary,
      marginTop: 24,
      marginBottom: 8,
    },
    emptyText: {
      fontSize: 16,
      color: colors.textSecondary,
      textAlign: "center",
      marginBottom: 32,
      fontWeight: "500",
    },
    shopNowBtn: {
      backgroundColor: colors.primaryBlue,
      paddingHorizontal: 32,
      paddingVertical: 14,
      borderRadius: 12,
      shadowColor: colors.primaryBlue,
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.25,
      shadowRadius: 6,
      elevation: 3,
    },
    shopNowText: {
      color: "#FFFFFF",
      fontSize: 16,
      fontWeight: "700",
    },

    // Main Layout
    mainRow: {
      flexDirection: screenWidth > 800 ? "row" : "column",
      paddingHorizontal: 16,
      paddingTop: 16,
      gap: 16,
      flex: 1,
    },
    leftColumn: {
      flex: 2,
      backgroundColor: colors.cardBackground,
      borderRadius: 12,
      padding: 20,
      borderWidth: 1,
      borderColor: colors.borderColor,
      shadowColor: colors.shadowColor,
      shadowOpacity: theme === "dark" ? 0.3 : 0.06,
      shadowOffset: { width: 0, height: 2 },
      shadowRadius: 8,
      elevation: 2,
    },
    rightColumn: {
      flex: 1,
      backgroundColor: colors.cardBackground,
      borderRadius: 12,
      padding: 20,
      borderWidth: 1,
      borderColor: colors.borderColor,
      shadowColor: colors.shadowColor,
      shadowOpacity: theme === "dark" ? 0.3 : 0.06,
      shadowOffset: { width: 0, height: 2 },
      shadowRadius: 8,
      elevation: 2,
      alignSelf: "flex-start",
      width: screenWidth > 800 ? "auto" : "100%",
    },

    // Cart Item
    itemCard: {
      flexDirection: "row",
      alignItems: "flex-start",
      borderBottomWidth: 1,
      borderBottomColor: colors.borderColor,
      paddingVertical: 16,
      position: "relative",
    },
    itemImg: {
      width: 100,
      height: 100,
      borderRadius: 12,
      backgroundColor: colors.inputBackground,
      marginRight: 16,
      borderWidth: 1,
      borderColor: colors.borderColor,
    },
    itemInfo: {
      flex: 1,
      paddingRight: 8,
    },
    itemName: {
      fontSize: 16,
      fontWeight: "700",
      color: colors.textPrimary,
      marginBottom: 4,
      lineHeight: 22,
    },
    itemDesc: {
      fontSize: 13,
      color: colors.textSecondary,
      marginBottom: 8,
      lineHeight: 18,
      fontWeight: "500",
    },
    typeBadge: {
      backgroundColor: colors.badgeBackground,
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 6,
      alignSelf: "flex-start",
      marginBottom: 8,
      borderWidth: 1,
      borderColor: colors.borderColor,
    },
    typeBadgeText: {
      fontSize: 11,
      fontWeight: "700",
      color: colors.badgeText,
      letterSpacing: 0.3,
    },
    itemBottom: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginTop: 8,
    },
    qtyRow: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: colors.inputBackground,
      borderRadius: 8,
      paddingHorizontal: 4,
      borderWidth: 1,
      borderColor: colors.borderColor,
    },
    qtyBtn: {
      width: 32,
      height: 32,
      justifyContent: "center",
      alignItems: "center",
    },
    qtyText: {
      fontSize: 15,
      fontWeight: "700",
      color: colors.textPrimary,
      marginHorizontal: 12,
      minWidth: 20,
      textAlign: "center",
    },
    itemPrice: {
      fontSize: 18,
      fontWeight: "700",
      color: colors.textPrimary,
    },
    removeBtn: {
      position: "absolute",
      top: 16,
      right: 0,
      padding: 8,
      backgroundColor: colors.removeButtonBg,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.removeButtonBorder,
    },

    // Order Summary
    summaryTitle: {
      fontSize: 20,
      fontWeight: "700",
      marginBottom: 16,
      color: colors.textPrimary,
      letterSpacing: -0.5,
    },
    summaryCard: {
      backgroundColor: colors.inputBackground,
      borderRadius: 12,
      padding: 16,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: colors.borderColor,
    },
    summaryRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginBottom: 12,
      alignItems: "center",
    },
    label: {
      fontSize: 14,
      color: colors.textSecondary,
      fontWeight: "600",
    },
    value: {
      fontSize: 15,
      color: colors.textPrimary,
      fontWeight: "700",
    },
    divider: {
      height: 1,
      backgroundColor: colors.borderColor,
      marginVertical: 12,
    },
    totalLabel: {
      fontSize: 17,
      fontWeight: "700",
      color: colors.textPrimary,
    },
    totalValue: {
      fontSize: 24,
      fontWeight: "700",
      color: colors.textPrimary,
    },

    // Discount
    discountRow: {
      backgroundColor: colors.discountBackground,
      padding: 12,
      borderRadius: 10,
      marginTop: 8,
      borderWidth: 1,
      borderColor: colors.discountBorder,
    },
    discountLabelRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    discountLabel: {
      fontSize: 14,
      fontWeight: "600",
      color: colors.discountText,
    },
    discountValue: {
      fontSize: 15,
      fontWeight: "700",
      color: colors.discountText,
    },

    // Coupon
    couponSection: {
      marginBottom: 20,
    },
    couponTitle: {
      fontSize: 16,
      fontWeight: "700",
      color: colors.textPrimary,
      marginBottom: 12,
    },
    couponRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    couponInput: {
      flex: 1,
      borderWidth: 1,
      borderColor: colors.borderColor,
      borderRadius: 10,
      paddingHorizontal: 14,
      paddingVertical: 12,
      fontSize: 14,
      color: colors.textPrimary,
      backgroundColor: colors.inputBackground,
      fontWeight: "600",
    },
    applyBtn: {
      backgroundColor: colors.primaryBlue,
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 10,
    },
    applyText: {
      color: "#FFFFFF",
      fontWeight: "700",
      fontSize: 14,
    },
    couponHint: {
      fontSize: 12,
      color: colors.textSecondary,
      marginTop: 8,
      fontStyle: "italic",
      fontWeight: "500",
    },

    // Checkout Button
    checkoutBtn: {
      backgroundColor: colors.primaryBlue,
      paddingVertical: 16,
      borderRadius: 12,
      marginBottom: 16,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      shadowColor: colors.primaryBlue,
      shadowOpacity: 0.3,
      shadowOffset: { width: 0, height: 4 },
      shadowRadius: 8,
      elevation: 4,
    },
    checkoutText: {
      color: "#FFFFFF",
      fontSize: 16,
      fontWeight: "700",
    },

    // Payment Methods
    paymentMethods: {
      borderTopWidth: 1,
      borderTopColor: colors.borderColor,
      paddingTop: 16,
    },
    paymentTitle: {
      fontSize: 13,
      color: colors.textSecondary,
      marginBottom: 12,
      textAlign: "center",
      fontWeight: "600",
    },
    paymentIcons: {
      flexDirection: "row",
      justifyContent: "center",
      gap: 16,
    },

    // Modal
    modalOverlay: {
      flex: 1,
      backgroundColor: colors.modalOverlay,
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: 20,
    },
    modalContent: {
      backgroundColor: colors.modalBackground,
      borderRadius: 20,
      maxHeight: "80%",
      width: "100%",
      maxWidth: 700,
      overflow: "hidden",
      shadowColor: colors.shadowColor,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.25,
      shadowRadius: 16,
      elevation: 15,
    },
    modalHeader: {
      paddingTop: 28,
      paddingBottom: 20,
      paddingHorizontal: 24,
      borderBottomWidth: 1,
      borderBottomColor: colors.borderColor,
      alignItems: "center",
      backgroundColor: colors.modalHeaderBg,
    },
    iconContainer: {
      width: 64,
      height: 64,
      borderRadius: 32,
      backgroundColor: colors.iconContainerBg,
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 14,
      shadowColor: colors.accentBlue,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 4,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: "700",
      color: colors.textPrimary,
      marginBottom: 6,
      letterSpacing: -0.3,
    },
    modalSubtitle: {
      fontSize: 14,
      color: colors.textSecondary,
      fontWeight: "400",
    },
    modalBody: {
      paddingHorizontal: 24,
      paddingVertical: 20,
    },
    modalSection: {
      marginBottom: 24,
    },
    modalSectionTitle: {
      fontSize: 15,
      fontWeight: "700",
      color: colors.textPrimary,
      marginBottom: 12,
      letterSpacing: -0.2,
    },
    itemsListContainer: {
      backgroundColor: colors.modalItemBg,
      borderRadius: 12,
      overflow: "hidden",
      borderWidth: 1,
      borderColor: colors.borderColor,
    },
    modalItemRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingHorizontal: 16,
      paddingVertical: 14,
      borderBottomWidth: 1,
      borderBottomColor: colors.borderColor,
    },
    modalItemInfo: {
      flex: 1,
      marginRight: 12,
    },
    modalItemName: {
      fontSize: 14,
      fontWeight: "600",
      color: colors.textPrimary,
      marginBottom: 4,
      lineHeight: 18,
    },
    modalItemType: {
      fontSize: 12,
      color: colors.textMuted,
      fontWeight: "500",
    },
    modalItemPrice: {
      fontSize: 14,
      fontWeight: "700",
      color: colors.accentBlue,
    },
    priceBreakdown: {
      backgroundColor: colors.priceBreakdownBg,
      borderRadius: 12,
      paddingHorizontal: 16,
      paddingVertical: 16,
      borderWidth: 1,
      borderColor: colors.borderColor,
    },
    priceRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingVertical: 6,
    },
    priceLabel: {
      fontSize: 14,
      color: colors.textSecondary,
      fontWeight: "500",
    },
    priceValue: {
      fontSize: 14,
      fontWeight: "600",
      color: colors.textPrimary,
    },
    discountPriceRow: {
      marginTop: 2,
      backgroundColor: colors.discountBackground,
      marginHorizontal: -16,
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 8,
    },
    discountPriceLabel: {
      flexDirection: "row",
      alignItems: "center",
    },
    discountPriceText: {
      fontSize: 14,
      color: colors.discountText,
      fontWeight: "600",
      marginLeft: 6,
    },
    discountPriceValue: {
      fontSize: 14,
      fontWeight: "700",
      color: colors.discountText,
    },
    priceDivider: {
      height: 1,
      backgroundColor: colors.borderColor,
      marginVertical: 12,
    },
    totalPriceRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingVertical: 8,
      marginTop: 4,
      backgroundColor: colors.totalRowBg,
      marginHorizontal: -16,
      paddingHorizontal: 16,
      borderRadius: 8,
    },
    totalPriceLabel: {
      fontSize: 15,
      fontWeight: "700",
      color: colors.textPrimary,
    },
    totalPriceValue: {
      fontSize: 18,
      fontWeight: "800",
      color: colors.accentBlue,
    },
    paymentMethodBox: {
      backgroundColor: colors.paymentMethodBg,
      borderRadius: 12,
      flexDirection: "row",
      padding: 16,
      alignItems: "flex-start",
      borderWidth: 1,
      borderColor: colors.paymentMethodBorder,
    },
    paymentMethodTitle: {
      fontSize: 14,
      fontWeight: "600",
      color: colors.textPrimary,
      marginBottom: 4,
    },
    paymentMethodText: {
      fontSize: 13,
      color: colors.textSecondary,
      lineHeight: 18,
    },
    modalFooter: {
      flexDirection: "row",
      gap: 12,
      paddingHorizontal: 24,
      paddingVertical: 20,
      borderTopWidth: 1,
      borderTopColor: colors.borderColor,
      backgroundColor: colors.modalFooterBg,
    },
    cancelBtn: {
      flex: 1,
      paddingVertical: 14,
      paddingHorizontal: 20,
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: colors.cancelButtonBorder,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.cancelButtonBg,
    },
    cancelBtnText: {
      fontSize: 15,
      fontWeight: "600",
      color: colors.textSecondary,
    },
    confirmBtn: {
      flex: 1.5,
      paddingVertical: 14,
      paddingHorizontal: 20,
      borderRadius: 12,
      backgroundColor: colors.confirmButtonBg,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      shadowColor: colors.confirmButtonBg,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 6,
    },
    confirmBtnText: {
      fontSize: 15,
      fontWeight: "700",
      color: "#FFFFFF",
    },
  });
};

export default getStyles;
