import { StyleSheet, Dimensions } from "react-native";
const screenWidth = Dimensions.get("window").width;

export const cartStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8FAFC",
  },

  // Header
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between", // chia 2 bên
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 16,
    backgroundColor: "rgba(255,255,255,0.96)",
    borderBottomWidth: 1,
    borderBottomColor: "#E2E8F0",
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 4,
  },

  leftHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12, // khoảng cách giữa icon và text
  },

  backBtn: {
    padding: 12,
    borderRadius: 30,
    backgroundColor: "#F8FAFC",
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 3,
  },

  headerTitle: {
    fontSize: 26,
    fontFamily: "Pacifico-Regular",
    color: "#084F8C",
    letterSpacing: -0.5,
  },

  continueText: {
    fontSize: 16,
    color: "#084F8C",
    fontFamily: "Pacifico-Regular",
  },

  // Empty State
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 32,
  },
  emptyTitle: {
    fontSize: 26,
    fontWeight: "700",
    color: "#1E293B",
    marginTop: 24,
    marginBottom: 8,
  },
  emptyText: {
    fontSize: 16,
    color: "#64748B",
    textAlign: "center",
    marginBottom: 32,
    fontWeight: "500",
  },
  shopNowBtn: {
    backgroundColor: "#084F8C",
    paddingHorizontal: 32,
    paddingVertical: 14,
    borderRadius: 12,
    shadowColor: "#084F8C",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 3,
  },
  shopNowText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "700",
  },

  // Main Layout
  mainRow: {
    flexDirection: screenWidth > 800 ? "row" : "column",
    paddingHorizontal: 16,
    paddingTop: 16,
    gap: 16,
    flex: 1,
  },
  leftColumn: {
    flex: 2,
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    padding: 20,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 8,
    elevation: 2,
  },
  rightColumn: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    padding: 20,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 8,
    elevation: 2,
    alignSelf: "flex-start",
    width: screenWidth > 800 ? "auto" : "100%",
  },

  // Cart Item
  itemCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    borderBottomWidth: 1,
    borderBottomColor: "#E2E8F0",
    paddingVertical: 16,
    position: "relative",
  },
  itemImg: {
    width: 100,
    height: 100,
    borderRadius: 12,
    backgroundColor: "#F8FAFC",
    marginRight: 16,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  itemInfo: {
    flex: 1,
    paddingRight: 8,
  },
  itemName: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1E293B",
    marginBottom: 4,
    lineHeight: 22,
  },
  itemDesc: {
    fontSize: 13,
    color: "#64748B",
    marginBottom: 8,
    lineHeight: 18,
    fontWeight: "500",
  },
  typeBadge: {
    backgroundColor: "#d3dde6ff",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
    alignSelf: "flex-start",
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  typeBadgeText: {
    fontSize: 11,
    fontWeight: "700",
    color: "black",
    letterSpacing: 0.3,
  },
  itemBottom: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 8,
  },
  qtyRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F8FAFC",
    borderRadius: 8,
    paddingHorizontal: 4,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  qtyBtn: {
    width: 32,
    height: 32,
    justifyContent: "center",
    alignItems: "center",
  },
  qtyText: {
    fontSize: 15,
    fontWeight: "700",
    color: "#1E293B",
    marginHorizontal: 12,
    minWidth: 20,
    textAlign: "center",
  },
  itemPrice: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1E293B",
  },
  removeBtn: {
    position: "absolute",
    top: 16,
    right: 0,
    padding: 8,
    backgroundColor: "#FEF2F2",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#FECACA",
  },

  // Order Summary
  summaryTitle: {
    fontSize: 20,
    fontWeight: "700",
    marginBottom: 16,
    color: "#1E293B",
    letterSpacing: -0.5,
  },
  summaryCard: {
    backgroundColor: "#F8FAFC",
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
    alignItems: "center",
  },
  label: {
    fontSize: 14,
    color: "#64748B",
    fontWeight: "600",
  },
  value: {
    fontSize: 15,
    color: "#1E293B",
    fontWeight: "700",
  },
  divider: {
    height: 1,
    backgroundColor: "#E2E8F0",
    marginVertical: 12,
  },
  totalLabel: {
    fontSize: 17,
    fontWeight: "700",
    color: "#1E293B",
  },
  totalValue: {
    fontSize: 24,
    fontWeight: "700",
    color: "#1E293B",
  },

  // Discount
  discountRow: {
    backgroundColor: "#F0FDF4",
    padding: 12,
    borderRadius: 10,
    marginTop: 8,
    borderWidth: 1,
    borderColor: "#BBF7D0",
  },
  discountLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  discountLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#16A34A",
  },
  discountValue: {
    fontSize: 15,
    fontWeight: "700",
    color: "#16A34A",
  },

  // Coupon
  couponSection: {
    marginBottom: 20,
  },
  couponTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1E293B",
    marginBottom: 12,
  },
  couponRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  couponInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
    color: "#1E293B",
    backgroundColor: "#F8FAFC",
    fontWeight: "600",
  },
  applyBtn: {
    backgroundColor: "#084F8C",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 10,
  },
  applyText: {
    color: "#FFFFFF",
    fontWeight: "700",
    fontSize: 14,
  },
  couponHint: {
    fontSize: 12,
    color: "#64748B",
    marginTop: 8,
    fontStyle: "italic",
    fontWeight: "500",
  },

  // Checkout Button
  checkoutBtn: {
    backgroundColor: "#084F8C",
    paddingVertical: 16,
    borderRadius: 12,
    marginBottom: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    shadowColor: "#084F8C",
    shadowOpacity: 0.3,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 8,
    elevation: 4,
  },
  checkoutText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "700",
  },

  // Payment Methods
  paymentMethods: {
    borderTopWidth: 1,
    borderTopColor: "#E2E8F0",
    paddingTop: 16,
  },
  paymentTitle: {
    fontSize: 13,
    color: "#64748B",
    marginBottom: 12,
    textAlign: "center",
    fontWeight: "600",
  },
  paymentIcons: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 16,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  modalContent: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    maxHeight: "80%",
    width: "100%",
    maxWidth: 700,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 15,
  },
  modalHeader: {
    paddingTop: 28,
    paddingBottom: 20,
    paddingHorizontal: 24,
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
    alignItems: "center",
    backgroundColor: "#FAFBFC",
  },
  iconContainer: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "#DBEAFE",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 14,
    shadowColor: "#1E40AF",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#111827",
    marginBottom: 6,
    letterSpacing: -0.3,
  },
  modalSubtitle: {
    fontSize: 14,
    color: "#6B7280",
    fontWeight: "400",
  },
  modalBody: {
    paddingHorizontal: 24,
    paddingVertical: 20,
  },
  modalSection: {
    marginBottom: 24,
  },
  modalSectionTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#374151",
    marginBottom: 12,
    letterSpacing: -0.2,
  },
  itemsListContainer: {
    backgroundColor: "#F9FAFB",
    borderRadius: 12,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  modalItemRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
  },
  modalItemInfo: {
    flex: 1,
    marginRight: 12,
  },
  modalItemName: {
    fontSize: 14,
    fontWeight: "600",
    color: "#111827",
    marginBottom: 4,
    lineHeight: 18,
  },
  modalItemType: {
    fontSize: 12,
    color: "#9CA3AF",
    fontWeight: "500",
  },
  modalItemPrice: {
    fontSize: 14,
    fontWeight: "700",
    color: "#1E40AF",
  },
  priceBreakdown: {
    backgroundColor: "#F9FAFB",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  priceRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 6,
  },
  priceLabel: {
    fontSize: 14,
    color: "#6B7280",
    fontWeight: "500",
  },
  priceValue: {
    fontSize: 14,
    fontWeight: "600",
    color: "#111827",
  },
  discountPriceRow: {
    marginTop: 2,
    backgroundColor: "#ECFDF5",
    marginHorizontal: -16,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
  },
  discountPriceLabel: {
    flexDirection: "row",
    alignItems: "center",
  },
  discountPriceText: {
    fontSize: 14,
    color: "#059669",
    fontWeight: "600",
    marginLeft: 6,
  },
  discountPriceValue: {
    fontSize: 14,
    fontWeight: "700",
    color: "#059669",
  },
  priceDivider: {
    height: 1,
    backgroundColor: "#D1D5DB",
    marginVertical: 12,
  },
  totalPriceRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 8,
    marginTop: 4,
    backgroundColor: "#EFF6FF",
    marginHorizontal: -16,
    paddingHorizontal: 16,
    borderRadius: 8,
  },
  totalPriceLabel: {
    fontSize: 15,
    fontWeight: "700",
    color: "#111827",
  },
  totalPriceValue: {
    fontSize: 18,
    fontWeight: "800",
    color: "#1E40AF",
  },
  paymentMethodBox: {
    backgroundColor: "#F5F3FF",
    borderRadius: 12,
    flexDirection: "row",
    padding: 16,
    alignItems: "flex-start",
    borderWidth: 1,
    borderColor: "#E9D5FF",
  },
  paymentMethodTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#111827",
    marginBottom: 4,
  },
  paymentMethodText: {
    fontSize: 13,
    color: "#6B7280",
    lineHeight: 18,
  },
  modalFooter: {
    flexDirection: "row",
    gap: 12,
    paddingHorizontal: 24,
    paddingVertical: 20,
    borderTopWidth: 1,
    borderTopColor: "#F3F4F6",
    backgroundColor: "#FAFBFC",
  },
  cancelBtn: {
    flex: 1,
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: "#D1D5DB",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
  },
  cancelBtnText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#4B5563",
  },
  confirmBtn: {
    flex: 1.5,
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 12,
    backgroundColor: "#1E40AF",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    shadowColor: "#1E40AF",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  confirmBtnText: {
    fontSize: 15,
    fontWeight: "700",
    color: "#FFFFFF",
  },
});
